//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.08 at 04:11:29 PM CET 
//


package project.xmlproject.model.zig;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Podnosioci_prijave"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Podnosilac_prijave" type="{http://www.ftn.uns.ac.rs/zig}TLice" maxOccurs="unbounded"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Punomocnik" type="{http://www.ftn.uns.ac.rs/zig}TLice" minOccurs="0"/&gt;
 *         &lt;element name="Zajednicki_predstavnik_podnosioca_prijave" type="{http://www.ftn.uns.ac.rs/zig}TLice" minOccurs="0"/&gt;
 *         &lt;element name="Zig"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Tip_ziga"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;choice&gt;
 *                             &lt;element name="Individualni_zig" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                             &lt;element name="Kolektivni_zig" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                             &lt;element name="Zig_garancije" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                           &lt;/choice&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Tip_znaka"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;choice&gt;
 *                             &lt;element name="Verbalni_znak" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                             &lt;element name="Graficki_znak" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                             &lt;element name="Kombinovani_znak" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                             &lt;element name="Trodimenzionalni_znak" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                             &lt;element name="Druga_vrsta_znaka" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                           &lt;/choice&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Izgled_znaka"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;attribute name="image_url" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Naznacene_boje" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="Boja" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Transliteracija_znaka" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="Prevod_znaka" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="Opis_znaka" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Klase_robe_i_usluga"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Klasa" type="{http://www.ftn.uns.ac.rs/zig}TKlasa" maxOccurs="45"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Pravo_prvenstva_i_osnov" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Placene_takse"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Osnovna_taksa" type="{http://www.ftn.uns.ac.rs/zig}TTaksa"/&gt;
 *                   &lt;element name="Taksa_za_klase"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="Vrednost" type="{http://www.ftn.uns.ac.rs/zig}TTaksa"/&gt;
 *                           &lt;/sequence&gt;
 *                           &lt;attribute name="broj_klasa" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Taksa_za_graficko_resenje" type="{http://www.ftn.uns.ac.rs/zig}TTaksa"/&gt;
 *                   &lt;element name="Ukupna_taksa" type="{http://www.ftn.uns.ac.rs/zig}TTaksa"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Podaci_o_prijavi"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Prilozi_uz_zahtev"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="Primerak_znaka"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;attribute name="naziv_dokumenta" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="Spisak_robe_i_usluga"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence maxOccurs="45"&gt;
 *                                       &lt;element name="Spisak"&gt;
 *                                         &lt;complexType&gt;
 *                                           &lt;complexContent&gt;
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                               &lt;sequence&gt;
 *                                                 &lt;element name="Klasa" type="{http://www.ftn.uns.ac.rs/zig}TKlasa"/&gt;
 *                                                 &lt;element name="Usluge"&gt;
 *                                                   &lt;complexType&gt;
 *                                                     &lt;complexContent&gt;
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                                         &lt;sequence&gt;
 *                                                           &lt;element name="Naziv" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/&gt;
 *                                                         &lt;/sequence&gt;
 *                                                       &lt;/restriction&gt;
 *                                                     &lt;/complexContent&gt;
 *                                                   &lt;/complexType&gt;
 *                                                 &lt;/element&gt;
 *                                               &lt;/sequence&gt;
 *                                             &lt;/restriction&gt;
 *                                           &lt;/complexContent&gt;
 *                                         &lt;/complexType&gt;
 *                                       &lt;/element&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="Punomocje" minOccurs="0"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;attribute name="naziv_dokumenta" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="Generalno_punomocje_ranije_prilozeno" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *                             &lt;element name="Punomocje_ce_biti_naknadno_dostavljeno" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *                             &lt;element name="Opsti_akt_o_kolektivnom_zigu" minOccurs="0"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;attribute name="naziv_dokumenta" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="Dokaz_o_pravu_prvenstva" minOccurs="0"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;attribute name="naziv_dokumenta" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="Dokaz_o_uplati_takse"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;attribute name="naziv_dokumenta" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Broj_prijave_ziga" type="{http://www.ftn.uns.ac.rs/zig}TBroj_prijave"/&gt;
 *                   &lt;element name="Datum_podnosenja" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "podnosiociPrijave",
    "punomocnik",
    "zajednickiPredstavnikPodnosiocaPrijave",
    "zig",
    "klaseRobeIUsluga",
    "pravoPrvenstvaIOsnov",
    "placeneTakse",
    "podaciOPrijavi"
})
@XmlRootElement(name = "Zahtev_za_priznanje_ziga")
public class ZahtevZaPriznanjeZiga {

    @XmlElement(name = "Podnosioci_prijave", required = true)
    protected ZahtevZaPriznanjeZiga.PodnosiociPrijave podnosiociPrijave;
    @XmlElement(name = "Punomocnik")
    protected TLice punomocnik;
    @XmlElement(name = "Zajednicki_predstavnik_podnosioca_prijave")
    protected TLice zajednickiPredstavnikPodnosiocaPrijave;
    @XmlElement(name = "Zig", required = true)
    protected ZahtevZaPriznanjeZiga.Zig zig;
    @XmlElement(name = "Klase_robe_i_usluga", required = true)
    protected ZahtevZaPriznanjeZiga.KlaseRobeIUsluga klaseRobeIUsluga;
    @XmlElement(name = "Pravo_prvenstva_i_osnov")
    protected String pravoPrvenstvaIOsnov;
    @XmlElement(name = "Placene_takse", required = true)
    protected ZahtevZaPriznanjeZiga.PlaceneTakse placeneTakse;
    @XmlElement(name = "Podaci_o_prijavi", required = true)
    protected ZahtevZaPriznanjeZiga.PodaciOPrijavi podaciOPrijavi;

    /**
     * Gets the value of the podnosiociPrijave property.
     * 
     * @return
     *     possible object is
     *     {@link ZahtevZaPriznanjeZiga.PodnosiociPrijave }
     *     
     */
    public ZahtevZaPriznanjeZiga.PodnosiociPrijave getPodnosiociPrijave() {
        return podnosiociPrijave;
    }

    /**
     * Sets the value of the podnosiociPrijave property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZahtevZaPriznanjeZiga.PodnosiociPrijave }
     *     
     */
    public void setPodnosiociPrijave(ZahtevZaPriznanjeZiga.PodnosiociPrijave value) {
        this.podnosiociPrijave = value;
    }

    /**
     * Gets the value of the punomocnik property.
     * 
     * @return
     *     possible object is
     *     {@link TLice }
     *     
     */
    public TLice getPunomocnik() {
        return punomocnik;
    }

    /**
     * Sets the value of the punomocnik property.
     * 
     * @param value
     *     allowed object is
     *     {@link TLice }
     *     
     */
    public void setPunomocnik(TLice value) {
        this.punomocnik = value;
    }

    /**
     * Gets the value of the zajednickiPredstavnikPodnosiocaPrijave property.
     * 
     * @return
     *     possible object is
     *     {@link TLice }
     *     
     */
    public TLice getZajednickiPredstavnikPodnosiocaPrijave() {
        return zajednickiPredstavnikPodnosiocaPrijave;
    }

    /**
     * Sets the value of the zajednickiPredstavnikPodnosiocaPrijave property.
     * 
     * @param value
     *     allowed object is
     *     {@link TLice }
     *     
     */
    public void setZajednickiPredstavnikPodnosiocaPrijave(TLice value) {
        this.zajednickiPredstavnikPodnosiocaPrijave = value;
    }

    /**
     * Gets the value of the zig property.
     * 
     * @return
     *     possible object is
     *     {@link ZahtevZaPriznanjeZiga.Zig }
     *     
     */
    public ZahtevZaPriznanjeZiga.Zig getZig() {
        return zig;
    }

    /**
     * Sets the value of the zig property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZahtevZaPriznanjeZiga.Zig }
     *     
     */
    public void setZig(ZahtevZaPriznanjeZiga.Zig value) {
        this.zig = value;
    }

    /**
     * Gets the value of the klaseRobeIUsluga property.
     * 
     * @return
     *     possible object is
     *     {@link ZahtevZaPriznanjeZiga.KlaseRobeIUsluga }
     *     
     */
    public ZahtevZaPriznanjeZiga.KlaseRobeIUsluga getKlaseRobeIUsluga() {
        return klaseRobeIUsluga;
    }

    /**
     * Sets the value of the klaseRobeIUsluga property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZahtevZaPriznanjeZiga.KlaseRobeIUsluga }
     *     
     */
    public void setKlaseRobeIUsluga(ZahtevZaPriznanjeZiga.KlaseRobeIUsluga value) {
        this.klaseRobeIUsluga = value;
    }

    /**
     * Gets the value of the pravoPrvenstvaIOsnov property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPravoPrvenstvaIOsnov() {
        return pravoPrvenstvaIOsnov;
    }

    /**
     * Sets the value of the pravoPrvenstvaIOsnov property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPravoPrvenstvaIOsnov(String value) {
        this.pravoPrvenstvaIOsnov = value;
    }

    /**
     * Gets the value of the placeneTakse property.
     * 
     * @return
     *     possible object is
     *     {@link ZahtevZaPriznanjeZiga.PlaceneTakse }
     *     
     */
    public ZahtevZaPriznanjeZiga.PlaceneTakse getPlaceneTakse() {
        return placeneTakse;
    }

    /**
     * Sets the value of the placeneTakse property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZahtevZaPriznanjeZiga.PlaceneTakse }
     *     
     */
    public void setPlaceneTakse(ZahtevZaPriznanjeZiga.PlaceneTakse value) {
        this.placeneTakse = value;
    }

    /**
     * Gets the value of the podaciOPrijavi property.
     * 
     * @return
     *     possible object is
     *     {@link ZahtevZaPriznanjeZiga.PodaciOPrijavi }
     *     
     */
    public ZahtevZaPriznanjeZiga.PodaciOPrijavi getPodaciOPrijavi() {
        return podaciOPrijavi;
    }

    /**
     * Sets the value of the podaciOPrijavi property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZahtevZaPriznanjeZiga.PodaciOPrijavi }
     *     
     */
    public void setPodaciOPrijavi(ZahtevZaPriznanjeZiga.PodaciOPrijavi value) {
        this.podaciOPrijavi = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Klasa" type="{http://www.ftn.uns.ac.rs/zig}TKlasa" maxOccurs="45"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "klasa"
    })
    public static class KlaseRobeIUsluga {

        @XmlElement(name = "Klasa", type = Integer.class)
        protected List<Integer> klasa;

        /**
         * Gets the value of the klasa property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the klasa property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getKlasa().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Integer }
         * 
         * 
         */
        public List<Integer> getKlasa() {
            if (klasa == null) {
                klasa = new ArrayList<Integer>();
            }
            return this.klasa;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Osnovna_taksa" type="{http://www.ftn.uns.ac.rs/zig}TTaksa"/&gt;
     *         &lt;element name="Taksa_za_klase"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="Vrednost" type="{http://www.ftn.uns.ac.rs/zig}TTaksa"/&gt;
     *                 &lt;/sequence&gt;
     *                 &lt;attribute name="broj_klasa" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Taksa_za_graficko_resenje" type="{http://www.ftn.uns.ac.rs/zig}TTaksa"/&gt;
     *         &lt;element name="Ukupna_taksa" type="{http://www.ftn.uns.ac.rs/zig}TTaksa"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "osnovnaTaksa",
        "taksaZaKlase",
        "taksaZaGrafickoResenje",
        "ukupnaTaksa"
    })
    public static class PlaceneTakse {

        @XmlElement(name = "Osnovna_taksa")
        protected double osnovnaTaksa;
        @XmlElement(name = "Taksa_za_klase", required = true)
        protected ZahtevZaPriznanjeZiga.PlaceneTakse.TaksaZaKlase taksaZaKlase;
        @XmlElement(name = "Taksa_za_graficko_resenje", defaultValue = "0")
        protected double taksaZaGrafickoResenje;
        @XmlElement(name = "Ukupna_taksa")
        protected double ukupnaTaksa;

        /**
         * Gets the value of the osnovnaTaksa property.
         * 
         */
        public double getOsnovnaTaksa() {
            return osnovnaTaksa;
        }

        /**
         * Sets the value of the osnovnaTaksa property.
         * 
         */
        public void setOsnovnaTaksa(double value) {
            this.osnovnaTaksa = value;
        }

        /**
         * Gets the value of the taksaZaKlase property.
         * 
         * @return
         *     possible object is
         *     {@link ZahtevZaPriznanjeZiga.PlaceneTakse.TaksaZaKlase }
         *     
         */
        public ZahtevZaPriznanjeZiga.PlaceneTakse.TaksaZaKlase getTaksaZaKlase() {
            return taksaZaKlase;
        }

        /**
         * Sets the value of the taksaZaKlase property.
         * 
         * @param value
         *     allowed object is
         *     {@link ZahtevZaPriznanjeZiga.PlaceneTakse.TaksaZaKlase }
         *     
         */
        public void setTaksaZaKlase(ZahtevZaPriznanjeZiga.PlaceneTakse.TaksaZaKlase value) {
            this.taksaZaKlase = value;
        }

        /**
         * Gets the value of the taksaZaGrafickoResenje property.
         * 
         */
        public double getTaksaZaGrafickoResenje() {
            return taksaZaGrafickoResenje;
        }

        /**
         * Sets the value of the taksaZaGrafickoResenje property.
         * 
         */
        public void setTaksaZaGrafickoResenje(double value) {
            this.taksaZaGrafickoResenje = value;
        }

        /**
         * Gets the value of the ukupnaTaksa property.
         * 
         */
        public double getUkupnaTaksa() {
            return ukupnaTaksa;
        }

        /**
         * Sets the value of the ukupnaTaksa property.
         * 
         */
        public void setUkupnaTaksa(double value) {
            this.ukupnaTaksa = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="Vrednost" type="{http://www.ftn.uns.ac.rs/zig}TTaksa"/&gt;
         *       &lt;/sequence&gt;
         *       &lt;attribute name="broj_klasa" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "vrednost"
        })
        public static class TaksaZaKlase {

            @XmlElement(name = "Vrednost")
            protected double vrednost;
            @XmlAttribute(name = "broj_klasa")
            protected Integer brojKlasa;

            /**
             * Gets the value of the vrednost property.
             * 
             */
            public double getVrednost() {
                return vrednost;
            }

            /**
             * Sets the value of the vrednost property.
             * 
             */
            public void setVrednost(double value) {
                this.vrednost = value;
            }

            /**
             * Gets the value of the brojKlasa property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getBrojKlasa() {
                return brojKlasa;
            }

            /**
             * Sets the value of the brojKlasa property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setBrojKlasa(Integer value) {
                this.brojKlasa = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Prilozi_uz_zahtev"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="Primerak_znaka"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;attribute name="naziv_dokumenta" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="Spisak_robe_i_usluga"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence maxOccurs="45"&gt;
     *                             &lt;element name="Spisak"&gt;
     *                               &lt;complexType&gt;
     *                                 &lt;complexContent&gt;
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                                     &lt;sequence&gt;
     *                                       &lt;element name="Klasa" type="{http://www.ftn.uns.ac.rs/zig}TKlasa"/&gt;
     *                                       &lt;element name="Usluge"&gt;
     *                                         &lt;complexType&gt;
     *                                           &lt;complexContent&gt;
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                                               &lt;sequence&gt;
     *                                                 &lt;element name="Naziv" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/&gt;
     *                                               &lt;/sequence&gt;
     *                                             &lt;/restriction&gt;
     *                                           &lt;/complexContent&gt;
     *                                         &lt;/complexType&gt;
     *                                       &lt;/element&gt;
     *                                     &lt;/sequence&gt;
     *                                   &lt;/restriction&gt;
     *                                 &lt;/complexContent&gt;
     *                               &lt;/complexType&gt;
     *                             &lt;/element&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="Punomocje" minOccurs="0"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;attribute name="naziv_dokumenta" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="Generalno_punomocje_ranije_prilozeno" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
     *                   &lt;element name="Punomocje_ce_biti_naknadno_dostavljeno" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
     *                   &lt;element name="Opsti_akt_o_kolektivnom_zigu" minOccurs="0"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;attribute name="naziv_dokumenta" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="Dokaz_o_pravu_prvenstva" minOccurs="0"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;attribute name="naziv_dokumenta" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="Dokaz_o_uplati_takse"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;attribute name="naziv_dokumenta" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Broj_prijave_ziga" type="{http://www.ftn.uns.ac.rs/zig}TBroj_prijave"/&gt;
     *         &lt;element name="Datum_podnosenja" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "priloziUzZahtev",
        "brojPrijaveZiga",
        "datumPodnosenja"
    })
    public static class PodaciOPrijavi {

        @XmlElement(name = "Prilozi_uz_zahtev", required = true)
        protected ZahtevZaPriznanjeZiga.PodaciOPrijavi.PriloziUzZahtev priloziUzZahtev;
        @XmlElement(name = "Broj_prijave_ziga", required = true)
        protected String brojPrijaveZiga;
        @XmlElement(name = "Datum_podnosenja", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar datumPodnosenja;

        /**
         * Gets the value of the priloziUzZahtev property.
         * 
         * @return
         *     possible object is
         *     {@link ZahtevZaPriznanjeZiga.PodaciOPrijavi.PriloziUzZahtev }
         *     
         */
        public ZahtevZaPriznanjeZiga.PodaciOPrijavi.PriloziUzZahtev getPriloziUzZahtev() {
            return priloziUzZahtev;
        }

        /**
         * Sets the value of the priloziUzZahtev property.
         * 
         * @param value
         *     allowed object is
         *     {@link ZahtevZaPriznanjeZiga.PodaciOPrijavi.PriloziUzZahtev }
         *     
         */
        public void setPriloziUzZahtev(ZahtevZaPriznanjeZiga.PodaciOPrijavi.PriloziUzZahtev value) {
            this.priloziUzZahtev = value;
        }

        /**
         * Gets the value of the brojPrijaveZiga property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBrojPrijaveZiga() {
            return brojPrijaveZiga;
        }

        /**
         * Sets the value of the brojPrijaveZiga property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBrojPrijaveZiga(String value) {
            this.brojPrijaveZiga = value;
        }

        /**
         * Gets the value of the datumPodnosenja property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDatumPodnosenja() {
            return datumPodnosenja;
        }

        /**
         * Sets the value of the datumPodnosenja property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDatumPodnosenja(XMLGregorianCalendar value) {
            this.datumPodnosenja = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="Primerak_znaka"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;attribute name="naziv_dokumenta" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="Spisak_robe_i_usluga"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence maxOccurs="45"&gt;
         *                   &lt;element name="Spisak"&gt;
         *                     &lt;complexType&gt;
         *                       &lt;complexContent&gt;
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                           &lt;sequence&gt;
         *                             &lt;element name="Klasa" type="{http://www.ftn.uns.ac.rs/zig}TKlasa"/&gt;
         *                             &lt;element name="Usluge"&gt;
         *                               &lt;complexType&gt;
         *                                 &lt;complexContent&gt;
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                                     &lt;sequence&gt;
         *                                       &lt;element name="Naziv" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/&gt;
         *                                     &lt;/sequence&gt;
         *                                   &lt;/restriction&gt;
         *                                 &lt;/complexContent&gt;
         *                               &lt;/complexType&gt;
         *                             &lt;/element&gt;
         *                           &lt;/sequence&gt;
         *                         &lt;/restriction&gt;
         *                       &lt;/complexContent&gt;
         *                     &lt;/complexType&gt;
         *                   &lt;/element&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="Punomocje" minOccurs="0"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;attribute name="naziv_dokumenta" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="Generalno_punomocje_ranije_prilozeno" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
         *         &lt;element name="Punomocje_ce_biti_naknadno_dostavljeno" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
         *         &lt;element name="Opsti_akt_o_kolektivnom_zigu" minOccurs="0"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;attribute name="naziv_dokumenta" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="Dokaz_o_pravu_prvenstva" minOccurs="0"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;attribute name="naziv_dokumenta" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="Dokaz_o_uplati_takse"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;attribute name="naziv_dokumenta" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "primerakZnaka",
            "spisakRobeIUsluga",
            "punomocje",
            "generalnoPunomocjeRanijePrilozeno",
            "punomocjeCeBitiNaknadnoDostavljeno",
            "opstiAktOKolektivnomZigu",
            "dokazOPravuPrvenstva",
            "dokazOUplatiTakse"
        })
        public static class PriloziUzZahtev {

            @XmlElement(name = "Primerak_znaka", required = true)
            protected ZahtevZaPriznanjeZiga.PodaciOPrijavi.PriloziUzZahtev.PrimerakZnaka primerakZnaka;
            @XmlElement(name = "Spisak_robe_i_usluga", required = true)
            protected ZahtevZaPriznanjeZiga.PodaciOPrijavi.PriloziUzZahtev.SpisakRobeIUsluga spisakRobeIUsluga;
            @XmlElement(name = "Punomocje")
            protected ZahtevZaPriznanjeZiga.PodaciOPrijavi.PriloziUzZahtev.Punomocje punomocje;
            @XmlElement(name = "Generalno_punomocje_ranije_prilozeno", defaultValue = "false")
            protected Boolean generalnoPunomocjeRanijePrilozeno;
            @XmlElement(name = "Punomocje_ce_biti_naknadno_dostavljeno", defaultValue = "false")
            protected Boolean punomocjeCeBitiNaknadnoDostavljeno;
            @XmlElement(name = "Opsti_akt_o_kolektivnom_zigu")
            protected ZahtevZaPriznanjeZiga.PodaciOPrijavi.PriloziUzZahtev.OpstiAktOKolektivnomZigu opstiAktOKolektivnomZigu;
            @XmlElement(name = "Dokaz_o_pravu_prvenstva")
            protected ZahtevZaPriznanjeZiga.PodaciOPrijavi.PriloziUzZahtev.DokazOPravuPrvenstva dokazOPravuPrvenstva;
            @XmlElement(name = "Dokaz_o_uplati_takse", required = true)
            protected ZahtevZaPriznanjeZiga.PodaciOPrijavi.PriloziUzZahtev.DokazOUplatiTakse dokazOUplatiTakse;

            /**
             * Gets the value of the primerakZnaka property.
             * 
             * @return
             *     possible object is
             *     {@link ZahtevZaPriznanjeZiga.PodaciOPrijavi.PriloziUzZahtev.PrimerakZnaka }
             *     
             */
            public ZahtevZaPriznanjeZiga.PodaciOPrijavi.PriloziUzZahtev.PrimerakZnaka getPrimerakZnaka() {
                return primerakZnaka;
            }

            /**
             * Sets the value of the primerakZnaka property.
             * 
             * @param value
             *     allowed object is
             *     {@link ZahtevZaPriznanjeZiga.PodaciOPrijavi.PriloziUzZahtev.PrimerakZnaka }
             *     
             */
            public void setPrimerakZnaka(ZahtevZaPriznanjeZiga.PodaciOPrijavi.PriloziUzZahtev.PrimerakZnaka value) {
                this.primerakZnaka = value;
            }

            /**
             * Gets the value of the spisakRobeIUsluga property.
             * 
             * @return
             *     possible object is
             *     {@link ZahtevZaPriznanjeZiga.PodaciOPrijavi.PriloziUzZahtev.SpisakRobeIUsluga }
             *     
             */
            public ZahtevZaPriznanjeZiga.PodaciOPrijavi.PriloziUzZahtev.SpisakRobeIUsluga getSpisakRobeIUsluga() {
                return spisakRobeIUsluga;
            }

            /**
             * Sets the value of the spisakRobeIUsluga property.
             * 
             * @param value
             *     allowed object is
             *     {@link ZahtevZaPriznanjeZiga.PodaciOPrijavi.PriloziUzZahtev.SpisakRobeIUsluga }
             *     
             */
            public void setSpisakRobeIUsluga(ZahtevZaPriznanjeZiga.PodaciOPrijavi.PriloziUzZahtev.SpisakRobeIUsluga value) {
                this.spisakRobeIUsluga = value;
            }

            /**
             * Gets the value of the punomocje property.
             * 
             * @return
             *     possible object is
             *     {@link ZahtevZaPriznanjeZiga.PodaciOPrijavi.PriloziUzZahtev.Punomocje }
             *     
             */
            public ZahtevZaPriznanjeZiga.PodaciOPrijavi.PriloziUzZahtev.Punomocje getPunomocje() {
                return punomocje;
            }

            /**
             * Sets the value of the punomocje property.
             * 
             * @param value
             *     allowed object is
             *     {@link ZahtevZaPriznanjeZiga.PodaciOPrijavi.PriloziUzZahtev.Punomocje }
             *     
             */
            public void setPunomocje(ZahtevZaPriznanjeZiga.PodaciOPrijavi.PriloziUzZahtev.Punomocje value) {
                this.punomocje = value;
            }

            /**
             * Gets the value of the generalnoPunomocjeRanijePrilozeno property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isGeneralnoPunomocjeRanijePrilozeno() {
                return generalnoPunomocjeRanijePrilozeno;
            }

            /**
             * Sets the value of the generalnoPunomocjeRanijePrilozeno property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setGeneralnoPunomocjeRanijePrilozeno(Boolean value) {
                this.generalnoPunomocjeRanijePrilozeno = value;
            }

            /**
             * Gets the value of the punomocjeCeBitiNaknadnoDostavljeno property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isPunomocjeCeBitiNaknadnoDostavljeno() {
                return punomocjeCeBitiNaknadnoDostavljeno;
            }

            /**
             * Sets the value of the punomocjeCeBitiNaknadnoDostavljeno property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setPunomocjeCeBitiNaknadnoDostavljeno(Boolean value) {
                this.punomocjeCeBitiNaknadnoDostavljeno = value;
            }

            /**
             * Gets the value of the opstiAktOKolektivnomZigu property.
             * 
             * @return
             *     possible object is
             *     {@link ZahtevZaPriznanjeZiga.PodaciOPrijavi.PriloziUzZahtev.OpstiAktOKolektivnomZigu }
             *     
             */
            public ZahtevZaPriznanjeZiga.PodaciOPrijavi.PriloziUzZahtev.OpstiAktOKolektivnomZigu getOpstiAktOKolektivnomZigu() {
                return opstiAktOKolektivnomZigu;
            }

            /**
             * Sets the value of the opstiAktOKolektivnomZigu property.
             * 
             * @param value
             *     allowed object is
             *     {@link ZahtevZaPriznanjeZiga.PodaciOPrijavi.PriloziUzZahtev.OpstiAktOKolektivnomZigu }
             *     
             */
            public void setOpstiAktOKolektivnomZigu(ZahtevZaPriznanjeZiga.PodaciOPrijavi.PriloziUzZahtev.OpstiAktOKolektivnomZigu value) {
                this.opstiAktOKolektivnomZigu = value;
            }

            /**
             * Gets the value of the dokazOPravuPrvenstva property.
             * 
             * @return
             *     possible object is
             *     {@link ZahtevZaPriznanjeZiga.PodaciOPrijavi.PriloziUzZahtev.DokazOPravuPrvenstva }
             *     
             */
            public ZahtevZaPriznanjeZiga.PodaciOPrijavi.PriloziUzZahtev.DokazOPravuPrvenstva getDokazOPravuPrvenstva() {
                return dokazOPravuPrvenstva;
            }

            /**
             * Sets the value of the dokazOPravuPrvenstva property.
             * 
             * @param value
             *     allowed object is
             *     {@link ZahtevZaPriznanjeZiga.PodaciOPrijavi.PriloziUzZahtev.DokazOPravuPrvenstva }
             *     
             */
            public void setDokazOPravuPrvenstva(ZahtevZaPriznanjeZiga.PodaciOPrijavi.PriloziUzZahtev.DokazOPravuPrvenstva value) {
                this.dokazOPravuPrvenstva = value;
            }

            /**
             * Gets the value of the dokazOUplatiTakse property.
             * 
             * @return
             *     possible object is
             *     {@link ZahtevZaPriznanjeZiga.PodaciOPrijavi.PriloziUzZahtev.DokazOUplatiTakse }
             *     
             */
            public ZahtevZaPriznanjeZiga.PodaciOPrijavi.PriloziUzZahtev.DokazOUplatiTakse getDokazOUplatiTakse() {
                return dokazOUplatiTakse;
            }

            /**
             * Sets the value of the dokazOUplatiTakse property.
             * 
             * @param value
             *     allowed object is
             *     {@link ZahtevZaPriznanjeZiga.PodaciOPrijavi.PriloziUzZahtev.DokazOUplatiTakse }
             *     
             */
            public void setDokazOUplatiTakse(ZahtevZaPriznanjeZiga.PodaciOPrijavi.PriloziUzZahtev.DokazOUplatiTakse value) {
                this.dokazOUplatiTakse = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;attribute name="naziv_dokumenta" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class DokazOPravuPrvenstva {

                @XmlAttribute(name = "naziv_dokumenta")
                protected String nazivDokumenta;

                /**
                 * Gets the value of the nazivDokumenta property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getNazivDokumenta() {
                    return nazivDokumenta;
                }

                /**
                 * Sets the value of the nazivDokumenta property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setNazivDokumenta(String value) {
                    this.nazivDokumenta = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;attribute name="naziv_dokumenta" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class DokazOUplatiTakse {

                @XmlAttribute(name = "naziv_dokumenta")
                protected String nazivDokumenta;

                /**
                 * Gets the value of the nazivDokumenta property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getNazivDokumenta() {
                    return nazivDokumenta;
                }

                /**
                 * Sets the value of the nazivDokumenta property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setNazivDokumenta(String value) {
                    this.nazivDokumenta = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;attribute name="naziv_dokumenta" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class OpstiAktOKolektivnomZigu {

                @XmlAttribute(name = "naziv_dokumenta")
                protected String nazivDokumenta;

                /**
                 * Gets the value of the nazivDokumenta property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getNazivDokumenta() {
                    return nazivDokumenta;
                }

                /**
                 * Sets the value of the nazivDokumenta property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setNazivDokumenta(String value) {
                    this.nazivDokumenta = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;attribute name="naziv_dokumenta" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class PrimerakZnaka {

                @XmlAttribute(name = "naziv_dokumenta")
                protected String nazivDokumenta;

                /**
                 * Gets the value of the nazivDokumenta property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getNazivDokumenta() {
                    return nazivDokumenta;
                }

                /**
                 * Sets the value of the nazivDokumenta property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setNazivDokumenta(String value) {
                    this.nazivDokumenta = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;attribute name="naziv_dokumenta" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Punomocje {

                @XmlAttribute(name = "naziv_dokumenta")
                protected String nazivDokumenta;

                /**
                 * Gets the value of the nazivDokumenta property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getNazivDokumenta() {
                    return nazivDokumenta;
                }

                /**
                 * Sets the value of the nazivDokumenta property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setNazivDokumenta(String value) {
                    this.nazivDokumenta = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence maxOccurs="45"&gt;
             *         &lt;element name="Spisak"&gt;
             *           &lt;complexType&gt;
             *             &lt;complexContent&gt;
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *                 &lt;sequence&gt;
             *                   &lt;element name="Klasa" type="{http://www.ftn.uns.ac.rs/zig}TKlasa"/&gt;
             *                   &lt;element name="Usluge"&gt;
             *                     &lt;complexType&gt;
             *                       &lt;complexContent&gt;
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *                           &lt;sequence&gt;
             *                             &lt;element name="Naziv" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/&gt;
             *                           &lt;/sequence&gt;
             *                         &lt;/restriction&gt;
             *                       &lt;/complexContent&gt;
             *                     &lt;/complexType&gt;
             *                   &lt;/element&gt;
             *                 &lt;/sequence&gt;
             *               &lt;/restriction&gt;
             *             &lt;/complexContent&gt;
             *           &lt;/complexType&gt;
             *         &lt;/element&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "spisak"
            })
            public static class SpisakRobeIUsluga {

                @XmlElement(name = "Spisak", required = true)
                protected List<ZahtevZaPriznanjeZiga.PodaciOPrijavi.PriloziUzZahtev.SpisakRobeIUsluga.Spisak> spisak;

                /**
                 * Gets the value of the spisak property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the spisak property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getSpisak().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link ZahtevZaPriznanjeZiga.PodaciOPrijavi.PriloziUzZahtev.SpisakRobeIUsluga.Spisak }
                 * 
                 * 
                 */
                public List<ZahtevZaPriznanjeZiga.PodaciOPrijavi.PriloziUzZahtev.SpisakRobeIUsluga.Spisak> getSpisak() {
                    if (spisak == null) {
                        spisak = new ArrayList<ZahtevZaPriznanjeZiga.PodaciOPrijavi.PriloziUzZahtev.SpisakRobeIUsluga.Spisak>();
                    }
                    return this.spisak;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType&gt;
                 *   &lt;complexContent&gt;
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                 *       &lt;sequence&gt;
                 *         &lt;element name="Klasa" type="{http://www.ftn.uns.ac.rs/zig}TKlasa"/&gt;
                 *         &lt;element name="Usluge"&gt;
                 *           &lt;complexType&gt;
                 *             &lt;complexContent&gt;
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                 *                 &lt;sequence&gt;
                 *                   &lt;element name="Naziv" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/&gt;
                 *                 &lt;/sequence&gt;
                 *               &lt;/restriction&gt;
                 *             &lt;/complexContent&gt;
                 *           &lt;/complexType&gt;
                 *         &lt;/element&gt;
                 *       &lt;/sequence&gt;
                 *     &lt;/restriction&gt;
                 *   &lt;/complexContent&gt;
                 * &lt;/complexType&gt;
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "klasa",
                    "usluge"
                })
                public static class Spisak {

                    @XmlElement(name = "Klasa")
                    protected int klasa;
                    @XmlElement(name = "Usluge", required = true)
                    protected ZahtevZaPriznanjeZiga.PodaciOPrijavi.PriloziUzZahtev.SpisakRobeIUsluga.Spisak.Usluge usluge;

                    /**
                     * Gets the value of the klasa property.
                     * 
                     */
                    public int getKlasa() {
                        return klasa;
                    }

                    /**
                     * Sets the value of the klasa property.
                     * 
                     */
                    public void setKlasa(int value) {
                        this.klasa = value;
                    }

                    /**
                     * Gets the value of the usluge property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link ZahtevZaPriznanjeZiga.PodaciOPrijavi.PriloziUzZahtev.SpisakRobeIUsluga.Spisak.Usluge }
                     *     
                     */
                    public ZahtevZaPriznanjeZiga.PodaciOPrijavi.PriloziUzZahtev.SpisakRobeIUsluga.Spisak.Usluge getUsluge() {
                        return usluge;
                    }

                    /**
                     * Sets the value of the usluge property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link ZahtevZaPriznanjeZiga.PodaciOPrijavi.PriloziUzZahtev.SpisakRobeIUsluga.Spisak.Usluge }
                     *     
                     */
                    public void setUsluge(ZahtevZaPriznanjeZiga.PodaciOPrijavi.PriloziUzZahtev.SpisakRobeIUsluga.Spisak.Usluge value) {
                        this.usluge = value;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType&gt;
                     *   &lt;complexContent&gt;
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                     *       &lt;sequence&gt;
                     *         &lt;element name="Naziv" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/&gt;
                     *       &lt;/sequence&gt;
                     *     &lt;/restriction&gt;
                     *   &lt;/complexContent&gt;
                     * &lt;/complexType&gt;
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "naziv"
                    })
                    public static class Usluge {

                        @XmlElement(name = "Naziv", required = true)
                        protected List<String> naziv;

                        /**
                         * Gets the value of the naziv property.
                         * 
                         * <p>
                         * This accessor method returns a reference to the live list,
                         * not a snapshot. Therefore any modification you make to the
                         * returned list will be present inside the JAXB object.
                         * This is why there is not a <CODE>set</CODE> method for the naziv property.
                         * 
                         * <p>
                         * For example, to add a new item, do as follows:
                         * <pre>
                         *    getNaziv().add(newItem);
                         * </pre>
                         * 
                         * 
                         * <p>
                         * Objects of the following type(s) are allowed in the list
                         * {@link String }
                         * 
                         * 
                         */
                        public List<String> getNaziv() {
                            if (naziv == null) {
                                naziv = new ArrayList<String>();
                            }
                            return this.naziv;
                        }

                    }

                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Podnosilac_prijave" type="{http://www.ftn.uns.ac.rs/zig}TLice" maxOccurs="unbounded"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "podnosilacPrijave"
    })
    public static class PodnosiociPrijave {

        @XmlElement(name = "Podnosilac_prijave", required = true)
        protected List<TLice> podnosilacPrijave;

        /**
         * Gets the value of the podnosilacPrijave property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the podnosilacPrijave property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPodnosilacPrijave().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TLice }
         * 
         * 
         */
        public List<TLice> getPodnosilacPrijave() {
            if (podnosilacPrijave == null) {
                podnosilacPrijave = new ArrayList<TLice>();
            }
            return this.podnosilacPrijave;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Tip_ziga"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;choice&gt;
     *                   &lt;element name="Individualni_zig" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *                   &lt;element name="Kolektivni_zig" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *                   &lt;element name="Zig_garancije" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *                 &lt;/choice&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Tip_znaka"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;choice&gt;
     *                   &lt;element name="Verbalni_znak" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *                   &lt;element name="Graficki_znak" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *                   &lt;element name="Kombinovani_znak" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *                   &lt;element name="Trodimenzionalni_znak" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *                   &lt;element name="Druga_vrsta_znaka" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *                 &lt;/choice&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Izgled_znaka"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;attribute name="image_url" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Naznacene_boje" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="Boja" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Transliteracija_znaka" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="Prevod_znaka" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="Opis_znaka" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "tipZiga",
        "tipZnaka",
        "izgledZnaka",
        "naznaceneBoje",
        "transliteracijaZnaka",
        "prevodZnaka",
        "opisZnaka"
    })
    public static class Zig {

        @XmlElement(name = "Tip_ziga", required = true)
        protected ZahtevZaPriznanjeZiga.Zig.TipZiga tipZiga;
        @XmlElement(name = "Tip_znaka", required = true)
        protected ZahtevZaPriznanjeZiga.Zig.TipZnaka tipZnaka;
        @XmlElement(name = "Izgled_znaka", required = true)
        protected ZahtevZaPriznanjeZiga.Zig.IzgledZnaka izgledZnaka;
        @XmlElement(name = "Naznacene_boje")
        protected ZahtevZaPriznanjeZiga.Zig.NaznaceneBoje naznaceneBoje;
        @XmlElement(name = "Transliteracija_znaka")
        protected String transliteracijaZnaka;
        @XmlElement(name = "Prevod_znaka")
        protected String prevodZnaka;
        @XmlElement(name = "Opis_znaka")
        protected String opisZnaka;

        /**
         * Gets the value of the tipZiga property.
         * 
         * @return
         *     possible object is
         *     {@link ZahtevZaPriznanjeZiga.Zig.TipZiga }
         *     
         */
        public ZahtevZaPriznanjeZiga.Zig.TipZiga getTipZiga() {
            return tipZiga;
        }

        /**
         * Sets the value of the tipZiga property.
         * 
         * @param value
         *     allowed object is
         *     {@link ZahtevZaPriznanjeZiga.Zig.TipZiga }
         *     
         */
        public void setTipZiga(ZahtevZaPriznanjeZiga.Zig.TipZiga value) {
            this.tipZiga = value;
        }

        /**
         * Gets the value of the tipZnaka property.
         * 
         * @return
         *     possible object is
         *     {@link ZahtevZaPriznanjeZiga.Zig.TipZnaka }
         *     
         */
        public ZahtevZaPriznanjeZiga.Zig.TipZnaka getTipZnaka() {
            return tipZnaka;
        }

        /**
         * Sets the value of the tipZnaka property.
         * 
         * @param value
         *     allowed object is
         *     {@link ZahtevZaPriznanjeZiga.Zig.TipZnaka }
         *     
         */
        public void setTipZnaka(ZahtevZaPriznanjeZiga.Zig.TipZnaka value) {
            this.tipZnaka = value;
        }

        /**
         * Gets the value of the izgledZnaka property.
         * 
         * @return
         *     possible object is
         *     {@link ZahtevZaPriznanjeZiga.Zig.IzgledZnaka }
         *     
         */
        public ZahtevZaPriznanjeZiga.Zig.IzgledZnaka getIzgledZnaka() {
            return izgledZnaka;
        }

        /**
         * Sets the value of the izgledZnaka property.
         * 
         * @param value
         *     allowed object is
         *     {@link ZahtevZaPriznanjeZiga.Zig.IzgledZnaka }
         *     
         */
        public void setIzgledZnaka(ZahtevZaPriznanjeZiga.Zig.IzgledZnaka value) {
            this.izgledZnaka = value;
        }

        /**
         * Gets the value of the naznaceneBoje property.
         * 
         * @return
         *     possible object is
         *     {@link ZahtevZaPriznanjeZiga.Zig.NaznaceneBoje }
         *     
         */
        public ZahtevZaPriznanjeZiga.Zig.NaznaceneBoje getNaznaceneBoje() {
            return naznaceneBoje;
        }

        /**
         * Sets the value of the naznaceneBoje property.
         * 
         * @param value
         *     allowed object is
         *     {@link ZahtevZaPriznanjeZiga.Zig.NaznaceneBoje }
         *     
         */
        public void setNaznaceneBoje(ZahtevZaPriznanjeZiga.Zig.NaznaceneBoje value) {
            this.naznaceneBoje = value;
        }

        /**
         * Gets the value of the transliteracijaZnaka property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTransliteracijaZnaka() {
            return transliteracijaZnaka;
        }

        /**
         * Sets the value of the transliteracijaZnaka property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTransliteracijaZnaka(String value) {
            this.transliteracijaZnaka = value;
        }

        /**
         * Gets the value of the prevodZnaka property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrevodZnaka() {
            return prevodZnaka;
        }

        /**
         * Sets the value of the prevodZnaka property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrevodZnaka(String value) {
            this.prevodZnaka = value;
        }

        /**
         * Gets the value of the opisZnaka property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOpisZnaka() {
            return opisZnaka;
        }

        /**
         * Sets the value of the opisZnaka property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOpisZnaka(String value) {
            this.opisZnaka = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;attribute name="image_url" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class IzgledZnaka {

            @XmlAttribute(name = "image_url")
            protected String imageUrl;

            /**
             * Gets the value of the imageUrl property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getImageUrl() {
                return imageUrl;
            }

            /**
             * Sets the value of the imageUrl property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setImageUrl(String value) {
                this.imageUrl = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="Boja" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "boja"
        })
        public static class NaznaceneBoje {

            @XmlElement(name = "Boja", required = true)
            protected List<String> boja;

            /**
             * Gets the value of the boja property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the boja property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getBoja().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getBoja() {
                if (boja == null) {
                    boja = new ArrayList<String>();
                }
                return this.boja;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;choice&gt;
         *         &lt;element name="Individualni_zig" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
         *         &lt;element name="Kolektivni_zig" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
         *         &lt;element name="Zig_garancije" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
         *       &lt;/choice&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "individualniZig",
            "kolektivniZig",
            "zigGarancije"
        })
        public static class TipZiga {

            @XmlElement(name = "Individualni_zig", defaultValue = "true")
            protected Boolean individualniZig;
            @XmlElement(name = "Kolektivni_zig", defaultValue = "false")
            protected Boolean kolektivniZig;
            @XmlElement(name = "Zig_garancije", defaultValue = "false")
            protected Boolean zigGarancije;

            /**
             * Gets the value of the individualniZig property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isIndividualniZig() {
                return individualniZig;
            }

            /**
             * Sets the value of the individualniZig property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setIndividualniZig(Boolean value) {
                this.individualniZig = value;
            }

            /**
             * Gets the value of the kolektivniZig property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isKolektivniZig() {
                return kolektivniZig;
            }

            /**
             * Sets the value of the kolektivniZig property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setKolektivniZig(Boolean value) {
                this.kolektivniZig = value;
            }

            /**
             * Gets the value of the zigGarancije property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isZigGarancije() {
                return zigGarancije;
            }

            /**
             * Sets the value of the zigGarancije property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setZigGarancije(Boolean value) {
                this.zigGarancije = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;choice&gt;
         *         &lt;element name="Verbalni_znak" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
         *         &lt;element name="Graficki_znak" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
         *         &lt;element name="Kombinovani_znak" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
         *         &lt;element name="Trodimenzionalni_znak" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
         *         &lt;element name="Druga_vrsta_znaka" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
         *       &lt;/choice&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "verbalniZnak",
            "grafickiZnak",
            "kombinovaniZnak",
            "trodimenzionalniZnak",
            "drugaVrstaZnaka"
        })
        public static class TipZnaka {

            @XmlElement(name = "Verbalni_znak", defaultValue = "true")
            protected Boolean verbalniZnak;
            @XmlElement(name = "Graficki_znak", defaultValue = "false")
            protected Boolean grafickiZnak;
            @XmlElement(name = "Kombinovani_znak", defaultValue = "false")
            protected Boolean kombinovaniZnak;
            @XmlElement(name = "Trodimenzionalni_znak", defaultValue = "false")
            protected Boolean trodimenzionalniZnak;
            @XmlElement(name = "Druga_vrsta_znaka", defaultValue = "false")
            protected Boolean drugaVrstaZnaka;

            /**
             * Gets the value of the verbalniZnak property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isVerbalniZnak() {
                return verbalniZnak;
            }

            /**
             * Sets the value of the verbalniZnak property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setVerbalniZnak(Boolean value) {
                this.verbalniZnak = value;
            }

            /**
             * Gets the value of the grafickiZnak property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isGrafickiZnak() {
                return grafickiZnak;
            }

            /**
             * Sets the value of the grafickiZnak property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setGrafickiZnak(Boolean value) {
                this.grafickiZnak = value;
            }

            /**
             * Gets the value of the kombinovaniZnak property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isKombinovaniZnak() {
                return kombinovaniZnak;
            }

            /**
             * Sets the value of the kombinovaniZnak property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setKombinovaniZnak(Boolean value) {
                this.kombinovaniZnak = value;
            }

            /**
             * Gets the value of the trodimenzionalniZnak property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isTrodimenzionalniZnak() {
                return trodimenzionalniZnak;
            }

            /**
             * Sets the value of the trodimenzionalniZnak property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setTrodimenzionalniZnak(Boolean value) {
                this.trodimenzionalniZnak = value;
            }

            /**
             * Gets the value of the drugaVrstaZnaka property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isDrugaVrstaZnaka() {
                return drugaVrstaZnaka;
            }

            /**
             * Sets the value of the drugaVrstaZnaka property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setDrugaVrstaZnaka(Boolean value) {
                this.drugaVrstaZnaka = value;
            }

        }

    }

}
