//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.22 at 12:51:07 PM CET 
//


package project.xmlproject.model.resenjeZahteva;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Datum_resenja" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Zahtev_je_prihvacen" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;choice&gt;
 *           &lt;element name="Sifra" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *           &lt;element name="Obrazlozenje" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element name="Referenca" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "datumResenja",
    "zahtevJePrihvacen",
    "sifra",
    "obrazlozenje",
    "referenca",
    "naziv"
})
@XmlRootElement(name = "Resenje_zahteva")
public class ResenjeZahteva {

    @XmlAttribute(name="refid")
    protected String refid;
    @XmlElement(name = "Datum_resenja", required = true)
    protected String datumResenja;
    @XmlElement(name = "Zahtev_je_prihvacen")
    protected boolean zahtevJePrihvacen;
    @XmlElement(name = "Sifra")
    protected String sifra;
    @XmlElement(name = "Obrazlozenje")
    protected String obrazlozenje;
    @XmlElement(name = "Referenca", required = true)
    protected String referenca;

    @XmlElement(name= "naziv", required = true)
    protected String naziv;

    public String getRefid() {
        return refid;
    }

    public void setRefId(String refid) {
        this.refid = refid;
    }

    /**
     * Gets the value of the datumResenja property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatumResenja() {
        return datumResenja;
    }

    /**
     * Sets the value of the datumResenja property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatumResenja(String value) {
        this.datumResenja = value;
    }

    /**
     * Gets the value of the zahtevJePrihvacen property.
     * 
     */
    public boolean isZahtevJePrihvacen() {
        return zahtevJePrihvacen;
    }

    /**
     * Sets the value of the zahtevJePrihvacen property.
     * 
     */
    public void setZahtevJePrihvacen(boolean value) {
        this.zahtevJePrihvacen = value;
    }

    /**
     * Gets the value of the sifra property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSifra() {
        return sifra;
    }

    /**
     * Sets the value of the sifra property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSifra(String value) {
        this.sifra = value;
    }

    /**
     * Gets the value of the obrazlozenje property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObrazlozenje() {
        return obrazlozenje;
    }

    /**
     * Sets the value of the obrazlozenje property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObrazlozenje(String value) {
        this.obrazlozenje = value;
    }

    /**
     * Gets the value of the referenca property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferenca() {
        return referenca;
    }

    /**
     * Sets the value of the referenca property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferenca(String value) {
        this.referenca = value;
    }
    public String getNaziv() {return naziv;}
    public void setNaziv(String naziv) {this.naziv = naziv;}
}
