//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.11.30 at 09:42:14 PM CET 
//


package project.xmlproject.model.patent;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.patent package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.patent
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjePatenta }
     * 
     */
    public ZahtevZaPriznanjePatenta createZahtevZaPriznanjePatenta() {
        return new ZahtevZaPriznanjePatenta();
    }

    /**
     * Create an instance of {@link DodatnaPrijava }
     * 
     */
    public DodatnaPrijava createDodatnaPrijava() {
        return new DodatnaPrijava();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjePatenta.Punomocnik }
     * 
     */
    public ZahtevZaPriznanjePatenta.Punomocnik createZahtevZaPriznanjePatentaPunomocnik() {
        return new ZahtevZaPriznanjePatenta.Punomocnik();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjePatenta.Podnosilac }
     * 
     */
    public ZahtevZaPriznanjePatenta.Podnosilac createZahtevZaPriznanjePatentaPodnosilac() {
        return new ZahtevZaPriznanjePatenta.Podnosilac();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjePatenta.Podnosilac.NacinDostavljanja }
     * 
     */
    public ZahtevZaPriznanjePatenta.Podnosilac.NacinDostavljanja createZahtevZaPriznanjePatentaPodnosilacNacinDostavljanja() {
        return new ZahtevZaPriznanjePatenta.Podnosilac.NacinDostavljanja();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjePatenta.PodaciOPrijavama }
     * 
     */
    public ZahtevZaPriznanjePatenta.PodaciOPrijavama createZahtevZaPriznanjePatentaPodaciOPrijavama() {
        return new ZahtevZaPriznanjePatenta.PodaciOPrijavama();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjePatenta.NazivPronalaska }
     * 
     */
    public ZahtevZaPriznanjePatenta.NazivPronalaska createZahtevZaPriznanjePatentaNazivPronalaska() {
        return new ZahtevZaPriznanjePatenta.NazivPronalaska();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjePatenta.Pronalazac }
     * 
     */
    public ZahtevZaPriznanjePatenta.Pronalazac createZahtevZaPriznanjePatentaPronalazac() {
        return new ZahtevZaPriznanjePatenta.Pronalazac();
    }

    /**
     * Create an instance of {@link Adresa }
     * 
     */
    public Adresa createAdresa() {
        return new Adresa();
    }

    /**
     * Create an instance of {@link KontaktPodaci }
     * 
     */
    public KontaktPodaci createKontaktPodaci() {
        return new KontaktPodaci();
    }

    /**
     * Create an instance of {@link NovaPrijava }
     * 
     */
    public NovaPrijava createNovaPrijava() {
        return new NovaPrijava();
    }

    /**
     * Create an instance of {@link DodatnaPrijava.TipPrijave }
     * 
     */
    public DodatnaPrijava.TipPrijave createDodatnaPrijavaTipPrijave() {
        return new DodatnaPrijava.TipPrijave();
    }

    /**
     * Create an instance of {@link PriznanjePravaPrvenstva }
     * 
     */
    public PriznanjePravaPrvenstva createPriznanjePravaPrvenstva() {
        return new PriznanjePravaPrvenstva();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjePatenta.Punomocnik.TipPunomocnika }
     * 
     */
    public ZahtevZaPriznanjePatenta.Punomocnik.TipPunomocnika createZahtevZaPriznanjePatentaPunomocnikTipPunomocnika() {
        return new ZahtevZaPriznanjePatenta.Punomocnik.TipPunomocnika();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjePatenta.Podnosilac.NacinDostavljanja.Elektronski }
     * 
     */
    public ZahtevZaPriznanjePatenta.Podnosilac.NacinDostavljanja.Elektronski createZahtevZaPriznanjePatentaPodnosilacNacinDostavljanjaElektronski() {
        return new ZahtevZaPriznanjePatenta.Podnosilac.NacinDostavljanja.Elektronski();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjePatenta.Podnosilac.NacinDostavljanja.Papirni }
     * 
     */
    public ZahtevZaPriznanjePatenta.Podnosilac.NacinDostavljanja.Papirni createZahtevZaPriznanjePatentaPodnosilacNacinDostavljanjaPapirni() {
        return new ZahtevZaPriznanjePatenta.Podnosilac.NacinDostavljanja.Papirni();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjePatenta.PodaciOPrijavama.PriznanjaPravaPrvenstva }
     * 
     */
    public ZahtevZaPriznanjePatenta.PodaciOPrijavama.PriznanjaPravaPrvenstva createZahtevZaPriznanjePatentaPodaciOPrijavamaPriznanjaPravaPrvenstva() {
        return new ZahtevZaPriznanjePatenta.PodaciOPrijavama.PriznanjaPravaPrvenstva();
    }

}
