//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.11.30 at 09:42:14 PM CET 
//


package rs.ac.uns.ftn.patent;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Tip_prijave"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;choice&gt;
 *                   &lt;element name="Dopunska_prijava" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
 *                   &lt;element name="Izdvojena_prijava" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
 *                 &lt;/choice&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Broj_prvobitne_prijave"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;pattern value="P[0-9]+"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Datum_podnosenja_prijave" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tipPrijave",
    "brojPrvobitnePrijave",
    "datumPodnosenjaPrijave"
})
@XmlRootElement(name = "Dodatna_prijava")
public class DodatnaPrijava {

    @XmlElement(name = "Tip_prijave", required = true)
    protected DodatnaPrijava.TipPrijave tipPrijave;
    @XmlElement(name = "Broj_prvobitne_prijave", required = true)
    protected String brojPrvobitnePrijave;
    @XmlElement(name = "Datum_podnosenja_prijave", required = true)
    protected String datumPodnosenjaPrijave;

    /**
     * Gets the value of the tipPrijave property.
     * 
     * @return
     *     possible object is
     *     {@link DodatnaPrijava.TipPrijave }
     *     
     */
    public DodatnaPrijava.TipPrijave getTipPrijave() {
        return tipPrijave;
    }

    /**
     * Sets the value of the tipPrijave property.
     * 
     * @param value
     *     allowed object is
     *     {@link DodatnaPrijava.TipPrijave }
     *     
     */
    public void setTipPrijave(DodatnaPrijava.TipPrijave value) {
        this.tipPrijave = value;
    }

    /**
     * Gets the value of the brojPrvobitnePrijave property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrojPrvobitnePrijave() {
        return brojPrvobitnePrijave;
    }

    /**
     * Sets the value of the brojPrvobitnePrijave property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrojPrvobitnePrijave(String value) {
        this.brojPrvobitnePrijave = value;
    }

    /**
     * Gets the value of the datumPodnosenjaPrijave property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatumPodnosenjaPrijave() {
        return datumPodnosenjaPrijave;
    }

    /**
     * Sets the value of the datumPodnosenjaPrijave property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatumPodnosenjaPrijave(String value) {
        this.datumPodnosenjaPrijave = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;choice&gt;
     *         &lt;element name="Dopunska_prijava" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
     *         &lt;element name="Izdvojena_prijava" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
     *       &lt;/choice&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dopunskaPrijava",
        "izdvojenaPrijava"
    })
    public static class TipPrijave {

        @XmlElement(name = "Dopunska_prijava")
        protected Object dopunskaPrijava;
        @XmlElement(name = "Izdvojena_prijava")
        protected Object izdvojenaPrijava;

        /**
         * Gets the value of the dopunskaPrijava property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getDopunskaPrijava() {
            return dopunskaPrijava;
        }

        /**
         * Sets the value of the dopunskaPrijava property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setDopunskaPrijava(Object value) {
            this.dopunskaPrijava = value;
        }

        /**
         * Gets the value of the izdvojenaPrijava property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getIzdvojenaPrijava() {
            return izdvojenaPrijava;
        }

        /**
         * Sets the value of the izdvojenaPrijava property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setIzdvojenaPrijava(Object value) {
            this.izdvojenaPrijava = value;
        }

    }

}
