//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.11.30 at 09:42:14 PM CET 
//


package rs.ac.uns.ftn.patent;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Podaci_o_prijavama"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element ref="{http://www.ftn.uns.ac.rs/patent}Nova_prijava"/&gt;
 *                   &lt;element ref="{http://www.ftn.uns.ac.rs/patent}Dodatna_prijava"/&gt;
 *                   &lt;element name="Priznanja_prava_prvenstva"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element ref="{http://www.ftn.uns.ac.rs/patent}Priznanje_prava_prvenstva" maxOccurs="unbounded"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Naziv_pronalaska"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Srpski_naziv" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="Engleski_naziv" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Podnosilac"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Naziv" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element ref="{http://www.ftn.uns.ac.rs/patent}Adresa"/&gt;
 *                   &lt;element ref="{http://www.ftn.uns.ac.rs/patent}Kontakt_podaci"/&gt;
 *                   &lt;element name="Drzavljanstvo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="Podnosilac_je_pronalazac" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                   &lt;element name="Nacin_dostavljanja"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;choice&gt;
 *                             &lt;element name="Elektronski"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="Email" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="Papirni"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element ref="{http://www.ftn.uns.ac.rs/patent}Adresa"/&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/choice&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Pronalazac"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Naziv" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element ref="{http://www.ftn.uns.ac.rs/patent}Adresa"/&gt;
 *                   &lt;element ref="{http://www.ftn.uns.ac.rs/patent}Kontakt_podaci"/&gt;
 *                   &lt;element name="Zeli_biti_u_prijavi" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Punomocnik"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Tip_punomocnika"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;choice&gt;
 *                             &lt;element name="Punomocnik_za_zastupanje" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
 *                             &lt;element name="Punomocnik_za_prijem_pismena" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
 *                           &lt;/choice&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Zajednicki_predstavnik" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                   &lt;element name="Naziv" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element ref="{http://www.ftn.uns.ac.rs/patent}Adresa"/&gt;
 *                   &lt;element ref="{http://www.ftn.uns.ac.rs/patent}Kontakt_podaci"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "podaciOPrijavama",
    "nazivPronalaska",
    "podnosilac",
    "pronalazac",
    "punomocnik"
})
@XmlRootElement(name = "Zahtev_za_priznanje_patenta")
public class ZahtevZaPriznanjePatenta {

    @XmlElement(name = "Podaci_o_prijavama", required = true)
    protected ZahtevZaPriznanjePatenta.PodaciOPrijavama podaciOPrijavama;
    @XmlElement(name = "Naziv_pronalaska", required = true)
    protected ZahtevZaPriznanjePatenta.NazivPronalaska nazivPronalaska;
    @XmlElement(name = "Podnosilac", required = true)
    protected ZahtevZaPriznanjePatenta.Podnosilac podnosilac;
    @XmlElement(name = "Pronalazac", required = true)
    protected ZahtevZaPriznanjePatenta.Pronalazac pronalazac;
    @XmlElement(name = "Punomocnik", required = true)
    protected ZahtevZaPriznanjePatenta.Punomocnik punomocnik;

    /**
     * Gets the value of the podaciOPrijavama property.
     * 
     * @return
     *     possible object is
     *     {@link ZahtevZaPriznanjePatenta.PodaciOPrijavama }
     *     
     */
    public ZahtevZaPriznanjePatenta.PodaciOPrijavama getPodaciOPrijavama() {
        return podaciOPrijavama;
    }

    /**
     * Sets the value of the podaciOPrijavama property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZahtevZaPriznanjePatenta.PodaciOPrijavama }
     *     
     */
    public void setPodaciOPrijavama(ZahtevZaPriznanjePatenta.PodaciOPrijavama value) {
        this.podaciOPrijavama = value;
    }

    /**
     * Gets the value of the nazivPronalaska property.
     * 
     * @return
     *     possible object is
     *     {@link ZahtevZaPriznanjePatenta.NazivPronalaska }
     *     
     */
    public ZahtevZaPriznanjePatenta.NazivPronalaska getNazivPronalaska() {
        return nazivPronalaska;
    }

    /**
     * Sets the value of the nazivPronalaska property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZahtevZaPriznanjePatenta.NazivPronalaska }
     *     
     */
    public void setNazivPronalaska(ZahtevZaPriznanjePatenta.NazivPronalaska value) {
        this.nazivPronalaska = value;
    }

    /**
     * Gets the value of the podnosilac property.
     * 
     * @return
     *     possible object is
     *     {@link ZahtevZaPriznanjePatenta.Podnosilac }
     *     
     */
    public ZahtevZaPriznanjePatenta.Podnosilac getPodnosilac() {
        return podnosilac;
    }

    /**
     * Sets the value of the podnosilac property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZahtevZaPriznanjePatenta.Podnosilac }
     *     
     */
    public void setPodnosilac(ZahtevZaPriznanjePatenta.Podnosilac value) {
        this.podnosilac = value;
    }

    /**
     * Gets the value of the pronalazac property.
     * 
     * @return
     *     possible object is
     *     {@link ZahtevZaPriznanjePatenta.Pronalazac }
     *     
     */
    public ZahtevZaPriznanjePatenta.Pronalazac getPronalazac() {
        return pronalazac;
    }

    /**
     * Sets the value of the pronalazac property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZahtevZaPriznanjePatenta.Pronalazac }
     *     
     */
    public void setPronalazac(ZahtevZaPriznanjePatenta.Pronalazac value) {
        this.pronalazac = value;
    }

    /**
     * Gets the value of the punomocnik property.
     * 
     * @return
     *     possible object is
     *     {@link ZahtevZaPriznanjePatenta.Punomocnik }
     *     
     */
    public ZahtevZaPriznanjePatenta.Punomocnik getPunomocnik() {
        return punomocnik;
    }

    /**
     * Sets the value of the punomocnik property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZahtevZaPriznanjePatenta.Punomocnik }
     *     
     */
    public void setPunomocnik(ZahtevZaPriznanjePatenta.Punomocnik value) {
        this.punomocnik = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Srpski_naziv" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="Engleski_naziv" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "srpskiNaziv",
        "engleskiNaziv"
    })
    public static class NazivPronalaska {

        @XmlElement(name = "Srpski_naziv", required = true)
        protected String srpskiNaziv;
        @XmlElement(name = "Engleski_naziv", required = true)
        protected String engleskiNaziv;

        /**
         * Gets the value of the srpskiNaziv property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSrpskiNaziv() {
            return srpskiNaziv;
        }

        /**
         * Sets the value of the srpskiNaziv property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSrpskiNaziv(String value) {
            this.srpskiNaziv = value;
        }

        /**
         * Gets the value of the engleskiNaziv property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEngleskiNaziv() {
            return engleskiNaziv;
        }

        /**
         * Sets the value of the engleskiNaziv property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEngleskiNaziv(String value) {
            this.engleskiNaziv = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element ref="{http://www.ftn.uns.ac.rs/patent}Nova_prijava"/&gt;
     *         &lt;element ref="{http://www.ftn.uns.ac.rs/patent}Dodatna_prijava"/&gt;
     *         &lt;element name="Priznanja_prava_prvenstva"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element ref="{http://www.ftn.uns.ac.rs/patent}Priznanje_prava_prvenstva" maxOccurs="unbounded"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "novaPrijava",
        "dodatnaPrijava",
        "priznanjaPravaPrvenstva"
    })
    public static class PodaciOPrijavama {

        @XmlElement(name = "Nova_prijava", required = true)
        protected NovaPrijava novaPrijava;
        @XmlElement(name = "Dodatna_prijava", required = true)
        protected DodatnaPrijava dodatnaPrijava;
        @XmlElement(name = "Priznanja_prava_prvenstva", required = true)
        protected ZahtevZaPriznanjePatenta.PodaciOPrijavama.PriznanjaPravaPrvenstva priznanjaPravaPrvenstva;

        /**
         * Gets the value of the novaPrijava property.
         * 
         * @return
         *     possible object is
         *     {@link NovaPrijava }
         *     
         */
        public NovaPrijava getNovaPrijava() {
            return novaPrijava;
        }

        /**
         * Sets the value of the novaPrijava property.
         * 
         * @param value
         *     allowed object is
         *     {@link NovaPrijava }
         *     
         */
        public void setNovaPrijava(NovaPrijava value) {
            this.novaPrijava = value;
        }

        /**
         * Gets the value of the dodatnaPrijava property.
         * 
         * @return
         *     possible object is
         *     {@link DodatnaPrijava }
         *     
         */
        public DodatnaPrijava getDodatnaPrijava() {
            return dodatnaPrijava;
        }

        /**
         * Sets the value of the dodatnaPrijava property.
         * 
         * @param value
         *     allowed object is
         *     {@link DodatnaPrijava }
         *     
         */
        public void setDodatnaPrijava(DodatnaPrijava value) {
            this.dodatnaPrijava = value;
        }

        /**
         * Gets the value of the priznanjaPravaPrvenstva property.
         * 
         * @return
         *     possible object is
         *     {@link ZahtevZaPriznanjePatenta.PodaciOPrijavama.PriznanjaPravaPrvenstva }
         *     
         */
        public ZahtevZaPriznanjePatenta.PodaciOPrijavama.PriznanjaPravaPrvenstva getPriznanjaPravaPrvenstva() {
            return priznanjaPravaPrvenstva;
        }

        /**
         * Sets the value of the priznanjaPravaPrvenstva property.
         * 
         * @param value
         *     allowed object is
         *     {@link ZahtevZaPriznanjePatenta.PodaciOPrijavama.PriznanjaPravaPrvenstva }
         *     
         */
        public void setPriznanjaPravaPrvenstva(ZahtevZaPriznanjePatenta.PodaciOPrijavama.PriznanjaPravaPrvenstva value) {
            this.priznanjaPravaPrvenstva = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element ref="{http://www.ftn.uns.ac.rs/patent}Priznanje_prava_prvenstva" maxOccurs="unbounded"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "priznanjePravaPrvenstva"
        })
        public static class PriznanjaPravaPrvenstva {

            @XmlElement(name = "Priznanje_prava_prvenstva", required = true)
            protected List<PriznanjePravaPrvenstva> priznanjePravaPrvenstva;

            /**
             * Gets the value of the priznanjePravaPrvenstva property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the priznanjePravaPrvenstva property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getPriznanjePravaPrvenstva().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link PriznanjePravaPrvenstva }
             * 
             * 
             */
            public List<PriznanjePravaPrvenstva> getPriznanjePravaPrvenstva() {
                if (priznanjePravaPrvenstva == null) {
                    priznanjePravaPrvenstva = new ArrayList<PriznanjePravaPrvenstva>();
                }
                return this.priznanjePravaPrvenstva;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Naziv" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element ref="{http://www.ftn.uns.ac.rs/patent}Adresa"/&gt;
     *         &lt;element ref="{http://www.ftn.uns.ac.rs/patent}Kontakt_podaci"/&gt;
     *         &lt;element name="Drzavljanstvo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="Podnosilac_je_pronalazac" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *         &lt;element name="Nacin_dostavljanja"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;choice&gt;
     *                   &lt;element name="Elektronski"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="Email" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="Papirni"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element ref="{http://www.ftn.uns.ac.rs/patent}Adresa"/&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/choice&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "naziv",
        "adresa",
        "kontaktPodaci",
        "drzavljanstvo",
        "podnosilacJePronalazac",
        "nacinDostavljanja"
    })
    public static class Podnosilac {

        @XmlElement(name = "Naziv", required = true)
        protected String naziv;
        @XmlElement(name = "Adresa", required = true)
        protected Adresa adresa;
        @XmlElement(name = "Kontakt_podaci", required = true)
        protected KontaktPodaci kontaktPodaci;
        @XmlElement(name = "Drzavljanstvo", required = true)
        protected String drzavljanstvo;
        @XmlElement(name = "Podnosilac_je_pronalazac", defaultValue = "false")
        protected boolean podnosilacJePronalazac;
        @XmlElement(name = "Nacin_dostavljanja", required = true)
        protected ZahtevZaPriznanjePatenta.Podnosilac.NacinDostavljanja nacinDostavljanja;

        /**
         * Gets the value of the naziv property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNaziv() {
            return naziv;
        }

        /**
         * Sets the value of the naziv property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNaziv(String value) {
            this.naziv = value;
        }

        /**
         * Gets the value of the adresa property.
         * 
         * @return
         *     possible object is
         *     {@link Adresa }
         *     
         */
        public Adresa getAdresa() {
            return adresa;
        }

        /**
         * Sets the value of the adresa property.
         * 
         * @param value
         *     allowed object is
         *     {@link Adresa }
         *     
         */
        public void setAdresa(Adresa value) {
            this.adresa = value;
        }

        /**
         * Gets the value of the kontaktPodaci property.
         * 
         * @return
         *     possible object is
         *     {@link KontaktPodaci }
         *     
         */
        public KontaktPodaci getKontaktPodaci() {
            return kontaktPodaci;
        }

        /**
         * Sets the value of the kontaktPodaci property.
         * 
         * @param value
         *     allowed object is
         *     {@link KontaktPodaci }
         *     
         */
        public void setKontaktPodaci(KontaktPodaci value) {
            this.kontaktPodaci = value;
        }

        /**
         * Gets the value of the drzavljanstvo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDrzavljanstvo() {
            return drzavljanstvo;
        }

        /**
         * Sets the value of the drzavljanstvo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDrzavljanstvo(String value) {
            this.drzavljanstvo = value;
        }

        /**
         * Gets the value of the podnosilacJePronalazac property.
         * 
         */
        public boolean isPodnosilacJePronalazac() {
            return podnosilacJePronalazac;
        }

        /**
         * Sets the value of the podnosilacJePronalazac property.
         * 
         */
        public void setPodnosilacJePronalazac(boolean value) {
            this.podnosilacJePronalazac = value;
        }

        /**
         * Gets the value of the nacinDostavljanja property.
         * 
         * @return
         *     possible object is
         *     {@link ZahtevZaPriznanjePatenta.Podnosilac.NacinDostavljanja }
         *     
         */
        public ZahtevZaPriznanjePatenta.Podnosilac.NacinDostavljanja getNacinDostavljanja() {
            return nacinDostavljanja;
        }

        /**
         * Sets the value of the nacinDostavljanja property.
         * 
         * @param value
         *     allowed object is
         *     {@link ZahtevZaPriznanjePatenta.Podnosilac.NacinDostavljanja }
         *     
         */
        public void setNacinDostavljanja(ZahtevZaPriznanjePatenta.Podnosilac.NacinDostavljanja value) {
            this.nacinDostavljanja = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;choice&gt;
         *         &lt;element name="Elektronski"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="Email" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="Papirni"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element ref="{http://www.ftn.uns.ac.rs/patent}Adresa"/&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/choice&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "elektronski",
            "papirni"
        })
        public static class NacinDostavljanja {

            @XmlElement(name = "Elektronski")
            protected ZahtevZaPriznanjePatenta.Podnosilac.NacinDostavljanja.Elektronski elektronski;
            @XmlElement(name = "Papirni")
            protected ZahtevZaPriznanjePatenta.Podnosilac.NacinDostavljanja.Papirni papirni;

            /**
             * Gets the value of the elektronski property.
             * 
             * @return
             *     possible object is
             *     {@link ZahtevZaPriznanjePatenta.Podnosilac.NacinDostavljanja.Elektronski }
             *     
             */
            public ZahtevZaPriznanjePatenta.Podnosilac.NacinDostavljanja.Elektronski getElektronski() {
                return elektronski;
            }

            /**
             * Sets the value of the elektronski property.
             * 
             * @param value
             *     allowed object is
             *     {@link ZahtevZaPriznanjePatenta.Podnosilac.NacinDostavljanja.Elektronski }
             *     
             */
            public void setElektronski(ZahtevZaPriznanjePatenta.Podnosilac.NacinDostavljanja.Elektronski value) {
                this.elektronski = value;
            }

            /**
             * Gets the value of the papirni property.
             * 
             * @return
             *     possible object is
             *     {@link ZahtevZaPriznanjePatenta.Podnosilac.NacinDostavljanja.Papirni }
             *     
             */
            public ZahtevZaPriznanjePatenta.Podnosilac.NacinDostavljanja.Papirni getPapirni() {
                return papirni;
            }

            /**
             * Sets the value of the papirni property.
             * 
             * @param value
             *     allowed object is
             *     {@link ZahtevZaPriznanjePatenta.Podnosilac.NacinDostavljanja.Papirni }
             *     
             */
            public void setPapirni(ZahtevZaPriznanjePatenta.Podnosilac.NacinDostavljanja.Papirni value) {
                this.papirni = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="Email" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "email"
            })
            public static class Elektronski {

                @XmlElement(name = "Email", required = true)
                protected String email;

                /**
                 * Gets the value of the email property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getEmail() {
                    return email;
                }

                /**
                 * Sets the value of the email property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setEmail(String value) {
                    this.email = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element ref="{http://www.ftn.uns.ac.rs/patent}Adresa"/&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "adresa"
            })
            public static class Papirni {

                @XmlElement(name = "Adresa", required = true)
                protected Adresa adresa;

                /**
                 * Gets the value of the adresa property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Adresa }
                 *     
                 */
                public Adresa getAdresa() {
                    return adresa;
                }

                /**
                 * Sets the value of the adresa property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Adresa }
                 *     
                 */
                public void setAdresa(Adresa value) {
                    this.adresa = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Naziv" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element ref="{http://www.ftn.uns.ac.rs/patent}Adresa"/&gt;
     *         &lt;element ref="{http://www.ftn.uns.ac.rs/patent}Kontakt_podaci"/&gt;
     *         &lt;element name="Zeli_biti_u_prijavi" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "naziv",
        "adresa",
        "kontaktPodaci",
        "zeliBitiUPrijavi"
    })
    public static class Pronalazac {

        @XmlElement(name = "Naziv", required = true)
        protected String naziv;
        @XmlElement(name = "Adresa", required = true)
        protected Adresa adresa;
        @XmlElement(name = "Kontakt_podaci", required = true)
        protected KontaktPodaci kontaktPodaci;
        @XmlElement(name = "Zeli_biti_u_prijavi", defaultValue = "true")
        protected boolean zeliBitiUPrijavi;

        /**
         * Gets the value of the naziv property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNaziv() {
            return naziv;
        }

        /**
         * Sets the value of the naziv property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNaziv(String value) {
            this.naziv = value;
        }

        /**
         * Gets the value of the adresa property.
         * 
         * @return
         *     possible object is
         *     {@link Adresa }
         *     
         */
        public Adresa getAdresa() {
            return adresa;
        }

        /**
         * Sets the value of the adresa property.
         * 
         * @param value
         *     allowed object is
         *     {@link Adresa }
         *     
         */
        public void setAdresa(Adresa value) {
            this.adresa = value;
        }

        /**
         * Gets the value of the kontaktPodaci property.
         * 
         * @return
         *     possible object is
         *     {@link KontaktPodaci }
         *     
         */
        public KontaktPodaci getKontaktPodaci() {
            return kontaktPodaci;
        }

        /**
         * Sets the value of the kontaktPodaci property.
         * 
         * @param value
         *     allowed object is
         *     {@link KontaktPodaci }
         *     
         */
        public void setKontaktPodaci(KontaktPodaci value) {
            this.kontaktPodaci = value;
        }

        /**
         * Gets the value of the zeliBitiUPrijavi property.
         * 
         */
        public boolean isZeliBitiUPrijavi() {
            return zeliBitiUPrijavi;
        }

        /**
         * Sets the value of the zeliBitiUPrijavi property.
         * 
         */
        public void setZeliBitiUPrijavi(boolean value) {
            this.zeliBitiUPrijavi = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Tip_punomocnika"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;choice&gt;
     *                   &lt;element name="Punomocnik_za_zastupanje" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
     *                   &lt;element name="Punomocnik_za_prijem_pismena" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
     *                 &lt;/choice&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Zajednicki_predstavnik" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *         &lt;element name="Naziv" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element ref="{http://www.ftn.uns.ac.rs/patent}Adresa"/&gt;
     *         &lt;element ref="{http://www.ftn.uns.ac.rs/patent}Kontakt_podaci"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "tipPunomocnika",
        "zajednickiPredstavnik",
        "naziv",
        "adresa",
        "kontaktPodaci"
    })
    public static class Punomocnik {

        @XmlElement(name = "Tip_punomocnika", required = true)
        protected ZahtevZaPriznanjePatenta.Punomocnik.TipPunomocnika tipPunomocnika;
        @XmlElement(name = "Zajednicki_predstavnik", defaultValue = "false")
        protected boolean zajednickiPredstavnik;
        @XmlElement(name = "Naziv", required = true)
        protected String naziv;
        @XmlElement(name = "Adresa", required = true)
        protected Adresa adresa;
        @XmlElement(name = "Kontakt_podaci", required = true)
        protected KontaktPodaci kontaktPodaci;

        /**
         * Gets the value of the tipPunomocnika property.
         * 
         * @return
         *     possible object is
         *     {@link ZahtevZaPriznanjePatenta.Punomocnik.TipPunomocnika }
         *     
         */
        public ZahtevZaPriznanjePatenta.Punomocnik.TipPunomocnika getTipPunomocnika() {
            return tipPunomocnika;
        }

        /**
         * Sets the value of the tipPunomocnika property.
         * 
         * @param value
         *     allowed object is
         *     {@link ZahtevZaPriznanjePatenta.Punomocnik.TipPunomocnika }
         *     
         */
        public void setTipPunomocnika(ZahtevZaPriznanjePatenta.Punomocnik.TipPunomocnika value) {
            this.tipPunomocnika = value;
        }

        /**
         * Gets the value of the zajednickiPredstavnik property.
         * 
         */
        public boolean isZajednickiPredstavnik() {
            return zajednickiPredstavnik;
        }

        /**
         * Sets the value of the zajednickiPredstavnik property.
         * 
         */
        public void setZajednickiPredstavnik(boolean value) {
            this.zajednickiPredstavnik = value;
        }

        /**
         * Gets the value of the naziv property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNaziv() {
            return naziv;
        }

        /**
         * Sets the value of the naziv property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNaziv(String value) {
            this.naziv = value;
        }

        /**
         * Gets the value of the adresa property.
         * 
         * @return
         *     possible object is
         *     {@link Adresa }
         *     
         */
        public Adresa getAdresa() {
            return adresa;
        }

        /**
         * Sets the value of the adresa property.
         * 
         * @param value
         *     allowed object is
         *     {@link Adresa }
         *     
         */
        public void setAdresa(Adresa value) {
            this.adresa = value;
        }

        /**
         * Gets the value of the kontaktPodaci property.
         * 
         * @return
         *     possible object is
         *     {@link KontaktPodaci }
         *     
         */
        public KontaktPodaci getKontaktPodaci() {
            return kontaktPodaci;
        }

        /**
         * Sets the value of the kontaktPodaci property.
         * 
         * @param value
         *     allowed object is
         *     {@link KontaktPodaci }
         *     
         */
        public void setKontaktPodaci(KontaktPodaci value) {
            this.kontaktPodaci = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;choice&gt;
         *         &lt;element name="Punomocnik_za_zastupanje" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
         *         &lt;element name="Punomocnik_za_prijem_pismena" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
         *       &lt;/choice&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "punomocnikZaZastupanje",
            "punomocnikZaPrijemPismena"
        })
        public static class TipPunomocnika {

            @XmlElement(name = "Punomocnik_za_zastupanje")
            protected Object punomocnikZaZastupanje;
            @XmlElement(name = "Punomocnik_za_prijem_pismena")
            protected Object punomocnikZaPrijemPismena;

            /**
             * Gets the value of the punomocnikZaZastupanje property.
             * 
             * @return
             *     possible object is
             *     {@link Object }
             *     
             */
            public Object getPunomocnikZaZastupanje() {
                return punomocnikZaZastupanje;
            }

            /**
             * Sets the value of the punomocnikZaZastupanje property.
             * 
             * @param value
             *     allowed object is
             *     {@link Object }
             *     
             */
            public void setPunomocnikZaZastupanje(Object value) {
                this.punomocnikZaZastupanje = value;
            }

            /**
             * Gets the value of the punomocnikZaPrijemPismena property.
             * 
             * @return
             *     possible object is
             *     {@link Object }
             *     
             */
            public Object getPunomocnikZaPrijemPismena() {
                return punomocnikZaPrijemPismena;
            }

            /**
             * Sets the value of the punomocnikZaPrijemPismena property.
             * 
             * @param value
             *     allowed object is
             *     {@link Object }
             *     
             */
            public void setPunomocnikZaPrijemPismena(Object value) {
                this.punomocnikZaPrijemPismena = value;
            }

        }

    }

}
