//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.31 at 09:25:02 PM CET 
//


package com.example.z1project.model.zig;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.zig package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.zig
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjeZiga }
     * 
     */
    public ZahtevZaPriznanjeZiga createZahtevZaPriznanjeZiga() {
        return new ZahtevZaPriznanjeZiga();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjeZiga.PodaciOPrijavi }
     * 
     */
    public ZahtevZaPriznanjeZiga.PodaciOPrijavi createZahtevZaPriznanjeZigaPodaciOPrijavi() {
        return new ZahtevZaPriznanjeZiga.PodaciOPrijavi();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjeZiga.PlaceneTakse }
     * 
     */
    public ZahtevZaPriznanjeZiga.PlaceneTakse createZahtevZaPriznanjeZigaPlaceneTakse() {
        return new ZahtevZaPriznanjeZiga.PlaceneTakse();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjeZiga.Zig }
     * 
     */
    public ZahtevZaPriznanjeZiga.Zig createZahtevZaPriznanjeZigaZig() {
        return new ZahtevZaPriznanjeZiga.Zig();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjeZiga.PodnosiociPrijave }
     * 
     */
    public ZahtevZaPriznanjeZiga.PodnosiociPrijave createZahtevZaPriznanjeZigaPodnosiociPrijave() {
        return new ZahtevZaPriznanjeZiga.PodnosiociPrijave();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjeZiga.KlaseRobeIUsluga }
     * 
     */
    public ZahtevZaPriznanjeZiga.KlaseRobeIUsluga createZahtevZaPriznanjeZigaKlaseRobeIUsluga() {
        return new ZahtevZaPriznanjeZiga.KlaseRobeIUsluga();
    }

    /**
     * Create an instance of {@link KontaktPodaci }
     * 
     */
    public KontaktPodaci createKontaktPodaci() {
        return new KontaktPodaci();
    }

    /**
     * Create an instance of {@link Adresa }
     * 
     */
    public Adresa createAdresa() {
        return new Adresa();
    }

    /**
     * Create an instance of {@link TFizickoLice }
     * 
     */
    public TFizickoLice createTFizickoLice() {
        return new TFizickoLice();
    }

    /**
     * Create an instance of {@link TPravnoLice }
     * 
     */
    public TPravnoLice createTPravnoLice() {
        return new TPravnoLice();
    }

    /**
     * Create an instance of {@link TPrilogUzZahtev }
     * 
     */
    public TPrilogUzZahtev createTPrilogUzZahtev() {
        return new TPrilogUzZahtev();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjeZiga.PodaciOPrijavi.PriloziUzZahtev }
     * 
     */
    public ZahtevZaPriznanjeZiga.PodaciOPrijavi.PriloziUzZahtev createZahtevZaPriznanjeZigaPodaciOPrijaviPriloziUzZahtev() {
        return new ZahtevZaPriznanjeZiga.PodaciOPrijavi.PriloziUzZahtev();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjeZiga.PlaceneTakse.TaksaZaKlase }
     * 
     */
    public ZahtevZaPriznanjeZiga.PlaceneTakse.TaksaZaKlase createZahtevZaPriznanjeZigaPlaceneTakseTaksaZaKlase() {
        return new ZahtevZaPriznanjeZiga.PlaceneTakse.TaksaZaKlase();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjeZiga.Zig.TipZiga }
     * 
     */
    public ZahtevZaPriznanjeZiga.Zig.TipZiga createZahtevZaPriznanjeZigaZigTipZiga() {
        return new ZahtevZaPriznanjeZiga.Zig.TipZiga();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjeZiga.Zig.TipZnaka }
     * 
     */
    public ZahtevZaPriznanjeZiga.Zig.TipZnaka createZahtevZaPriznanjeZigaZigTipZnaka() {
        return new ZahtevZaPriznanjeZiga.Zig.TipZnaka();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjeZiga.Zig.IzgledZnaka }
     * 
     */
    public ZahtevZaPriznanjeZiga.Zig.IzgledZnaka createZahtevZaPriznanjeZigaZigIzgledZnaka() {
        return new ZahtevZaPriznanjeZiga.Zig.IzgledZnaka();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjeZiga.Zig.NaznaceneBoje }
     * 
     */
    public ZahtevZaPriznanjeZiga.Zig.NaznaceneBoje createZahtevZaPriznanjeZigaZigNaznaceneBoje() {
        return new ZahtevZaPriznanjeZiga.Zig.NaznaceneBoje();
    }

}
