//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.05 at 03:21:19 PM CET 
//


package com.example.z1project.model.zig;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="broj_resenja_zahteva" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="datum_resenja" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="zahtev_je_prihvacen" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="ime_sluzbenika" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="prezime_sluzbenika" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;choice&gt;
 *           &lt;element name="sifra" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *           &lt;element name="obrazlozenje" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element name="referenca" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="qr" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "brojResenjaZahteva",
    "datumResenja",
    "zahtevJePrihvacen",
    "imeSluzbenika",
    "prezimeSluzbenika",
    "sifra",
    "obrazlozenje",
    "referenca"
})
@XmlRootElement(name = "resenje_zahteva")
public class ResenjeZahteva {

    @XmlElement(name = "broj_resenja_zahteva", required = true)
    protected String brojResenjaZahteva;
    @XmlElement(name = "datum_resenja", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumResenja;
    @XmlElement(name = "zahtev_je_prihvacen")
    protected boolean zahtevJePrihvacen;
    @XmlElement(name = "ime_sluzbenika", required = true)
    protected String imeSluzbenika;
    @XmlElement(name = "prezime_sluzbenika", required = true)
    protected String prezimeSluzbenika;
    protected String sifra;
    protected String obrazlozenje;
    @XmlElement(required = true)
    protected String referenca;
    @XmlAttribute(name = "qr")
    protected String qr;

    /**
     * Gets the value of the brojResenjaZahteva property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrojResenjaZahteva() {
        return brojResenjaZahteva;
    }

    /**
     * Sets the value of the brojResenjaZahteva property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrojResenjaZahteva(String value) {
        this.brojResenjaZahteva = value;
    }

    /**
     * Gets the value of the datumResenja property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumResenja() {
        return datumResenja;
    }

    /**
     * Sets the value of the datumResenja property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumResenja(XMLGregorianCalendar value) {
        this.datumResenja = value;
    }

    /**
     * Gets the value of the zahtevJePrihvacen property.
     * 
     */
    public boolean isZahtevJePrihvacen() {
        return zahtevJePrihvacen;
    }

    /**
     * Sets the value of the zahtevJePrihvacen property.
     * 
     */
    public void setZahtevJePrihvacen(boolean value) {
        this.zahtevJePrihvacen = value;
    }

    /**
     * Gets the value of the imeSluzbenika property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImeSluzbenika() {
        return imeSluzbenika;
    }

    /**
     * Sets the value of the imeSluzbenika property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImeSluzbenika(String value) {
        this.imeSluzbenika = value;
    }

    /**
     * Gets the value of the prezimeSluzbenika property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrezimeSluzbenika() {
        return prezimeSluzbenika;
    }

    /**
     * Sets the value of the prezimeSluzbenika property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrezimeSluzbenika(String value) {
        this.prezimeSluzbenika = value;
    }

    /**
     * Gets the value of the sifra property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSifra() {
        return sifra;
    }

    /**
     * Sets the value of the sifra property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSifra(String value) {
        this.sifra = value;
    }

    /**
     * Gets the value of the obrazlozenje property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObrazlozenje() {
        return obrazlozenje;
    }

    /**
     * Sets the value of the obrazlozenje property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObrazlozenje(String value) {
        this.obrazlozenje = value;
    }

    /**
     * Gets the value of the referenca property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferenca() {
        return referenca;
    }

    /**
     * Sets the value of the referenca property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferenca(String value) {
        this.referenca = value;
    }

    /**
     * Gets the value of the qr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQr() {
        return qr;
    }

    /**
     * Sets the value of the qr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQr(String value) {
        this.qr = value;
    }

}
