//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.02 at 08:57:14 PM CET 
//


package com.example.z1project.model.zig;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TPrilog_uz_zahtev complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TPrilog_uz_zahtev"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="naziv_dokumenta" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="putanja_dokumenta" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TPrilog_uz_zahtev")
public class TPrilogUzZahtev {

    @XmlAttribute(name = "naziv_dokumenta")
    protected String nazivDokumenta;
    @XmlAttribute(name = "putanja_dokumenta")
    protected String putanjaDokumenta;

    /**
     * Gets the value of the nazivDokumenta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNazivDokumenta() {
        return nazivDokumenta;
    }

    /**
     * Sets the value of the nazivDokumenta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazivDokumenta(String value) {
        this.nazivDokumenta = value;
    }

    /**
     * Gets the value of the putanjaDokumenta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPutanjaDokumenta() {
        return putanjaDokumenta;
    }

    /**
     * Sets the value of the putanjaDokumenta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPutanjaDokumenta(String value) {
        this.putanjaDokumenta = value;
    }

}
