//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.05 at 04:57:55 PM CET 
//


package com.example.z1project.model.zig;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Podnosioci_prijave"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Podnosilac_prijave" type="{http://www.ftn.uns.ac.rs/zig}TLice" maxOccurs="unbounded"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Punomocnik" type="{http://www.ftn.uns.ac.rs/zig}TFizicko_lice" minOccurs="0"/&gt;
 *         &lt;element name="Zajednicki_predstavnik_podnosioca_prijave" type="{http://www.ftn.uns.ac.rs/zig}TLice" minOccurs="0"/&gt;
 *         &lt;element name="Zig"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Tip_ziga"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;choice&gt;
 *                             &lt;element name="Individualni_zig" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                             &lt;element name="Kolektivni_zig" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                             &lt;element name="Zig_garancije" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                           &lt;/choice&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Tip_znaka"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;choice&gt;
 *                             &lt;element name="Verbalni_znak" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                             &lt;element name="Graficki_znak" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                             &lt;element name="Kombinovani_znak" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                             &lt;element name="Trodimenzionalni_znak" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                             &lt;element name="Druga_vrsta_znaka" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                           &lt;/choice&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Izgled_znaka"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;attribute name="image_url" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Naznacene_boje" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="Boja" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Transliteracija_znaka" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="Prevod_znaka" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="Opis_znaka" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Klase_robe_i_usluga"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Klasa" type="{http://www.ftn.uns.ac.rs/zig}TKlasa" maxOccurs="45"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Pravo_prvenstva_i_osnov" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Placene_takse"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Osnovna_taksa" type="{http://www.ftn.uns.ac.rs/zig}TTaksa"/&gt;
 *                   &lt;element name="Taksa_za_klase"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="Vrednost" type="{http://www.ftn.uns.ac.rs/zig}TTaksa"/&gt;
 *                           &lt;/sequence&gt;
 *                           &lt;attribute name="broj_klasa" type="{http://www.ftn.uns.ac.rs/zig}TKlasa" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Taksa_za_graficko_resenje" type="{http://www.ftn.uns.ac.rs/zig}TTaksa"/&gt;
 *                   &lt;element name="Ukupna_taksa" type="{http://www.ftn.uns.ac.rs/zig}TTaksa"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Podaci_o_prijavi"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Prilozi_uz_zahtev"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="Primerak_znaka" type="{http://www.ftn.uns.ac.rs/zig}TPrilog_uz_zahtev"/&gt;
 *                             &lt;element name="Spisak_robe_i_usluga" type="{http://www.ftn.uns.ac.rs/zig}TPrilog_uz_zahtev"/&gt;
 *                             &lt;element name="Punomocje" type="{http://www.ftn.uns.ac.rs/zig}TPrilog_uz_zahtev" minOccurs="0"/&gt;
 *                             &lt;element name="Generalno_punomocje_ranije_prilozeno" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *                             &lt;element name="Punomocje_ce_biti_naknadno_dostavljeno" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *                             &lt;element name="Opsti_akt_o_kolektivnom_zigu" type="{http://www.ftn.uns.ac.rs/zig}TPrilog_uz_zahtev" minOccurs="0"/&gt;
 *                             &lt;element name="Dokaz_o_pravu_prvenstva" type="{http://www.ftn.uns.ac.rs/zig}TPrilog_uz_zahtev" minOccurs="0"/&gt;
 *                             &lt;element name="Dokaz_o_uplati_takse" type="{http://www.ftn.uns.ac.rs/zig}TPrilog_uz_zahtev"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Broj_prijave_ziga" type="{http://www.ftn.uns.ac.rs/zig}TBroj_prijave"/&gt;
 *                   &lt;element name="Datum_podnosenja" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                   &lt;element name="Datum_prihvatanja" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="qr_html" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="qr_pdf" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="is_pdf" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "podnosiociPrijave",
    "punomocnik",
    "zajednickiPredstavnikPodnosiocaPrijave",
    "zig",
    "klaseRobeIUsluga",
    "pravoPrvenstvaIOsnov",
    "placeneTakse",
    "podaciOPrijavi"
})
@XmlRootElement(name = "Zahtev_za_priznanje_ziga")
public class ZahtevZaPriznanjeZiga {

    @XmlElement(name = "Podnosioci_prijave", required = true)
    protected PodnosiociPrijave podnosiociPrijave;
    @XmlElement(name = "Punomocnik")
    protected TFizickoLice punomocnik;
    @XmlElement(name = "Zajednicki_predstavnik_podnosioca_prijave")
    protected TLice zajednickiPredstavnikPodnosiocaPrijave;
    @XmlElement(name = "Zig", required = true)
    protected Zig zig;
    @XmlElement(name = "Klase_robe_i_usluga", required = true)
    protected KlaseRobeIUsluga klaseRobeIUsluga;
    @XmlElement(name = "Pravo_prvenstva_i_osnov")
    protected String pravoPrvenstvaIOsnov;
    @XmlElement(name = "Placene_takse", required = true)
    protected PlaceneTakse placeneTakse;
    @XmlElement(name = "Podaci_o_prijavi", required = true)
    protected PodaciOPrijavi podaciOPrijavi;
    @XmlAttribute(name = "qr_html")
    protected String qrHtml;
    @XmlAttribute(name = "qr_pdf")
    protected String qrPdf;
    @XmlAttribute(name = "is_pdf")
    protected Boolean isPdf;

    /**
     * Gets the value of the podnosiociPrijave property.
     * 
     * @return
     *     possible object is
     *     {@link PodnosiociPrijave }
     *     
     */
    public PodnosiociPrijave getPodnosiociPrijave() {
        return podnosiociPrijave;
    }

    /**
     * Sets the value of the podnosiociPrijave property.
     * 
     * @param value
     *     allowed object is
     *     {@link PodnosiociPrijave }
     *     
     */
    public void setPodnosiociPrijave(PodnosiociPrijave value) {
        this.podnosiociPrijave = value;
    }

    /**
     * Gets the value of the punomocnik property.
     * 
     * @return
     *     possible object is
     *     {@link TFizickoLice }
     *     
     */
    public TFizickoLice getPunomocnik() {
        return punomocnik;
    }

    /**
     * Sets the value of the punomocnik property.
     * 
     * @param value
     *     allowed object is
     *     {@link TFizickoLice }
     *     
     */
    public void setPunomocnik(TFizickoLice value) {
        this.punomocnik = value;
    }

    /**
     * Gets the value of the zajednickiPredstavnikPodnosiocaPrijave property.
     * 
     * @return
     *     possible object is
     *     {@link TLice }
     *     
     */
    public TLice getZajednickiPredstavnikPodnosiocaPrijave() {
        return zajednickiPredstavnikPodnosiocaPrijave;
    }

    /**
     * Sets the value of the zajednickiPredstavnikPodnosiocaPrijave property.
     * 
     * @param value
     *     allowed object is
     *     {@link TLice }
     *     
     */
    public void setZajednickiPredstavnikPodnosiocaPrijave(TLice value) {
        this.zajednickiPredstavnikPodnosiocaPrijave = value;
    }

    /**
     * Gets the value of the zig property.
     * 
     * @return
     *     possible object is
     *     {@link Zig }
     *     
     */
    public Zig getZig() {
        return zig;
    }

    /**
     * Sets the value of the zig property.
     * 
     * @param value
     *     allowed object is
     *     {@link Zig }
     *     
     */
    public void setZig(Zig value) {
        this.zig = value;
    }

    /**
     * Gets the value of the klaseRobeIUsluga property.
     * 
     * @return
     *     possible object is
     *     {@link KlaseRobeIUsluga }
     *     
     */
    public KlaseRobeIUsluga getKlaseRobeIUsluga() {
        return klaseRobeIUsluga;
    }

    /**
     * Sets the value of the klaseRobeIUsluga property.
     * 
     * @param value
     *     allowed object is
     *     {@link KlaseRobeIUsluga }
     *     
     */
    public void setKlaseRobeIUsluga(KlaseRobeIUsluga value) {
        this.klaseRobeIUsluga = value;
    }

    /**
     * Gets the value of the pravoPrvenstvaIOsnov property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPravoPrvenstvaIOsnov() {
        return pravoPrvenstvaIOsnov;
    }

    /**
     * Sets the value of the pravoPrvenstvaIOsnov property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPravoPrvenstvaIOsnov(String value) {
        this.pravoPrvenstvaIOsnov = value;
    }

    /**
     * Gets the value of the placeneTakse property.
     * 
     * @return
     *     possible object is
     *     {@link PlaceneTakse }
     *     
     */
    public PlaceneTakse getPlaceneTakse() {
        return placeneTakse;
    }

    /**
     * Sets the value of the placeneTakse property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlaceneTakse }
     *     
     */
    public void setPlaceneTakse(PlaceneTakse value) {
        this.placeneTakse = value;
    }

    /**
     * Gets the value of the podaciOPrijavi property.
     * 
     * @return
     *     possible object is
     *     {@link PodaciOPrijavi }
     *     
     */
    public PodaciOPrijavi getPodaciOPrijavi() {
        return podaciOPrijavi;
    }

    /**
     * Sets the value of the podaciOPrijavi property.
     * 
     * @param value
     *     allowed object is
     *     {@link PodaciOPrijavi }
     *     
     */
    public void setPodaciOPrijavi(PodaciOPrijavi value) {
        this.podaciOPrijavi = value;
    }

    /**
     * Gets the value of the qrHtml property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQrHtml() {
        return qrHtml;
    }

    /**
     * Sets the value of the qrHtml property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQrHtml(String value) {
        this.qrHtml = value;
    }

    /**
     * Gets the value of the qrPdf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQrPdf() {
        return qrPdf;
    }

    /**
     * Sets the value of the qrPdf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQrPdf(String value) {
        this.qrPdf = value;
    }

    /**
     * Gets the value of the isPdf property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsPdf() {
        return isPdf;
    }

    /**
     * Sets the value of the isPdf property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsPdf(Boolean value) {
        this.isPdf = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Klasa" type="{http://www.ftn.uns.ac.rs/zig}TKlasa" maxOccurs="45"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "klasa"
    })
    public static class KlaseRobeIUsluga {

        @XmlElement(name = "Klasa", type = Integer.class)
        protected List<Integer> klasa;

        /**
         * Gets the value of the klasa property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the klasa property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getKlasa().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Integer }
         * 
         * 
         */
        public List<Integer> getKlasa() {
            if (klasa == null) {
                klasa = new ArrayList<Integer>();
            }
            return this.klasa;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Osnovna_taksa" type="{http://www.ftn.uns.ac.rs/zig}TTaksa"/&gt;
     *         &lt;element name="Taksa_za_klase"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="Vrednost" type="{http://www.ftn.uns.ac.rs/zig}TTaksa"/&gt;
     *                 &lt;/sequence&gt;
     *                 &lt;attribute name="broj_klasa" type="{http://www.ftn.uns.ac.rs/zig}TKlasa" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Taksa_za_graficko_resenje" type="{http://www.ftn.uns.ac.rs/zig}TTaksa"/&gt;
     *         &lt;element name="Ukupna_taksa" type="{http://www.ftn.uns.ac.rs/zig}TTaksa"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "osnovnaTaksa",
        "taksaZaKlase",
        "taksaZaGrafickoResenje",
        "ukupnaTaksa"
    })
    public static class PlaceneTakse {

        @XmlElement(name = "Osnovna_taksa")
        protected double osnovnaTaksa;
        @XmlElement(name = "Taksa_za_klase", required = true)
        protected TaksaZaKlase taksaZaKlase;
        @XmlElement(name = "Taksa_za_graficko_resenje")
        protected double taksaZaGrafickoResenje;
        @XmlElement(name = "Ukupna_taksa")
        protected double ukupnaTaksa;

        /**
         * Gets the value of the osnovnaTaksa property.
         * 
         */
        public double getOsnovnaTaksa() {
            return osnovnaTaksa;
        }

        /**
         * Sets the value of the osnovnaTaksa property.
         * 
         */
        public void setOsnovnaTaksa(double value) {
            this.osnovnaTaksa = value;
        }

        /**
         * Gets the value of the taksaZaKlase property.
         * 
         * @return
         *     possible object is
         *     {@link TaksaZaKlase }
         *     
         */
        public TaksaZaKlase getTaksaZaKlase() {
            return taksaZaKlase;
        }

        /**
         * Sets the value of the taksaZaKlase property.
         * 
         * @param value
         *     allowed object is
         *     {@link TaksaZaKlase }
         *     
         */
        public void setTaksaZaKlase(TaksaZaKlase value) {
            this.taksaZaKlase = value;
        }

        /**
         * Gets the value of the taksaZaGrafickoResenje property.
         * 
         */
        public double getTaksaZaGrafickoResenje() {
            return taksaZaGrafickoResenje;
        }

        /**
         * Sets the value of the taksaZaGrafickoResenje property.
         * 
         */
        public void setTaksaZaGrafickoResenje(double value) {
            this.taksaZaGrafickoResenje = value;
        }

        /**
         * Gets the value of the ukupnaTaksa property.
         * 
         */
        public double getUkupnaTaksa() {
            return ukupnaTaksa;
        }

        /**
         * Sets the value of the ukupnaTaksa property.
         * 
         */
        public void setUkupnaTaksa(double value) {
            this.ukupnaTaksa = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="Vrednost" type="{http://www.ftn.uns.ac.rs/zig}TTaksa"/&gt;
         *       &lt;/sequence&gt;
         *       &lt;attribute name="broj_klasa" type="{http://www.ftn.uns.ac.rs/zig}TKlasa" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "vrednost"
        })
        public static class TaksaZaKlase {

            @XmlElement(name = "Vrednost")
            protected double vrednost;
            @XmlAttribute(name = "broj_klasa")
            protected Integer brojKlasa;

            /**
             * Gets the value of the vrednost property.
             * 
             */
            public double getVrednost() {
                return vrednost;
            }

            /**
             * Sets the value of the vrednost property.
             * 
             */
            public void setVrednost(double value) {
                this.vrednost = value;
            }

            /**
             * Gets the value of the brojKlasa property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getBrojKlasa() {
                return brojKlasa;
            }

            /**
             * Sets the value of the brojKlasa property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setBrojKlasa(Integer value) {
                this.brojKlasa = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Prilozi_uz_zahtev"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="Primerak_znaka" type="{http://www.ftn.uns.ac.rs/zig}TPrilog_uz_zahtev"/&gt;
     *                   &lt;element name="Spisak_robe_i_usluga" type="{http://www.ftn.uns.ac.rs/zig}TPrilog_uz_zahtev"/&gt;
     *                   &lt;element name="Punomocje" type="{http://www.ftn.uns.ac.rs/zig}TPrilog_uz_zahtev" minOccurs="0"/&gt;
     *                   &lt;element name="Generalno_punomocje_ranije_prilozeno" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
     *                   &lt;element name="Punomocje_ce_biti_naknadno_dostavljeno" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
     *                   &lt;element name="Opsti_akt_o_kolektivnom_zigu" type="{http://www.ftn.uns.ac.rs/zig}TPrilog_uz_zahtev" minOccurs="0"/&gt;
     *                   &lt;element name="Dokaz_o_pravu_prvenstva" type="{http://www.ftn.uns.ac.rs/zig}TPrilog_uz_zahtev" minOccurs="0"/&gt;
     *                   &lt;element name="Dokaz_o_uplati_takse" type="{http://www.ftn.uns.ac.rs/zig}TPrilog_uz_zahtev"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Broj_prijave_ziga" type="{http://www.ftn.uns.ac.rs/zig}TBroj_prijave"/&gt;
     *         &lt;element name="Datum_podnosenja" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
     *         &lt;element name="Datum_prihvatanja" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "priloziUzZahtev",
        "brojPrijaveZiga",
        "datumPodnosenja",
        "datumPrihvatanja"
    })
    public static class PodaciOPrijavi {

        @XmlElement(name = "Prilozi_uz_zahtev", required = true)
        protected PriloziUzZahtev priloziUzZahtev;
        @XmlElement(name = "Broj_prijave_ziga", required = true)
        protected String brojPrijaveZiga;
        @XmlElement(name = "Datum_podnosenja", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar datumPodnosenja;
        @XmlElement(name = "Datum_prihvatanja", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar datumPrihvatanja;

        /**
         * Gets the value of the priloziUzZahtev property.
         * 
         * @return
         *     possible object is
         *     {@link PriloziUzZahtev }
         *     
         */
        public PriloziUzZahtev getPriloziUzZahtev() {
            return priloziUzZahtev;
        }

        /**
         * Sets the value of the priloziUzZahtev property.
         * 
         * @param value
         *     allowed object is
         *     {@link PriloziUzZahtev }
         *     
         */
        public void setPriloziUzZahtev(PriloziUzZahtev value) {
            this.priloziUzZahtev = value;
        }

        /**
         * Gets the value of the brojPrijaveZiga property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBrojPrijaveZiga() {
            return brojPrijaveZiga;
        }

        /**
         * Sets the value of the brojPrijaveZiga property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBrojPrijaveZiga(String value) {
            this.brojPrijaveZiga = value;
        }

        /**
         * Gets the value of the datumPodnosenja property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDatumPodnosenja() {
            return datumPodnosenja;
        }

        /**
         * Sets the value of the datumPodnosenja property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDatumPodnosenja(XMLGregorianCalendar value) {
            this.datumPodnosenja = value;
        }

        /**
         * Gets the value of the datumPrihvatanja property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDatumPrihvatanja() {
            return datumPrihvatanja;
        }

        /**
         * Sets the value of the datumPrihvatanja property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDatumPrihvatanja(XMLGregorianCalendar value) {
            this.datumPrihvatanja = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="Primerak_znaka" type="{http://www.ftn.uns.ac.rs/zig}TPrilog_uz_zahtev"/&gt;
         *         &lt;element name="Spisak_robe_i_usluga" type="{http://www.ftn.uns.ac.rs/zig}TPrilog_uz_zahtev"/&gt;
         *         &lt;element name="Punomocje" type="{http://www.ftn.uns.ac.rs/zig}TPrilog_uz_zahtev" minOccurs="0"/&gt;
         *         &lt;element name="Generalno_punomocje_ranije_prilozeno" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
         *         &lt;element name="Punomocje_ce_biti_naknadno_dostavljeno" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
         *         &lt;element name="Opsti_akt_o_kolektivnom_zigu" type="{http://www.ftn.uns.ac.rs/zig}TPrilog_uz_zahtev" minOccurs="0"/&gt;
         *         &lt;element name="Dokaz_o_pravu_prvenstva" type="{http://www.ftn.uns.ac.rs/zig}TPrilog_uz_zahtev" minOccurs="0"/&gt;
         *         &lt;element name="Dokaz_o_uplati_takse" type="{http://www.ftn.uns.ac.rs/zig}TPrilog_uz_zahtev"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "primerakZnaka",
            "spisakRobeIUsluga",
            "punomocje",
            "generalnoPunomocjeRanijePrilozeno",
            "punomocjeCeBitiNaknadnoDostavljeno",
            "opstiAktOKolektivnomZigu",
            "dokazOPravuPrvenstva",
            "dokazOUplatiTakse"
        })
        public static class PriloziUzZahtev {

            @XmlElement(name = "Primerak_znaka", required = true)
            protected TPrilogUzZahtev primerakZnaka;
            @XmlElement(name = "Spisak_robe_i_usluga", required = true)
            protected TPrilogUzZahtev spisakRobeIUsluga;
            @XmlElement(name = "Punomocje")
            protected TPrilogUzZahtev punomocje;
            @XmlElement(name = "Generalno_punomocje_ranije_prilozeno", defaultValue = "false")
            protected Boolean generalnoPunomocjeRanijePrilozeno;
            @XmlElement(name = "Punomocje_ce_biti_naknadno_dostavljeno", defaultValue = "false")
            protected Boolean punomocjeCeBitiNaknadnoDostavljeno;
            @XmlElement(name = "Opsti_akt_o_kolektivnom_zigu")
            protected TPrilogUzZahtev opstiAktOKolektivnomZigu;
            @XmlElement(name = "Dokaz_o_pravu_prvenstva")
            protected TPrilogUzZahtev dokazOPravuPrvenstva;
            @XmlElement(name = "Dokaz_o_uplati_takse", required = true)
            protected TPrilogUzZahtev dokazOUplatiTakse;

            /**
             * Gets the value of the primerakZnaka property.
             * 
             * @return
             *     possible object is
             *     {@link TPrilogUzZahtev }
             *     
             */
            public TPrilogUzZahtev getPrimerakZnaka() {
                return primerakZnaka;
            }

            /**
             * Sets the value of the primerakZnaka property.
             * 
             * @param value
             *     allowed object is
             *     {@link TPrilogUzZahtev }
             *     
             */
            public void setPrimerakZnaka(TPrilogUzZahtev value) {
                this.primerakZnaka = value;
            }

            /**
             * Gets the value of the spisakRobeIUsluga property.
             * 
             * @return
             *     possible object is
             *     {@link TPrilogUzZahtev }
             *     
             */
            public TPrilogUzZahtev getSpisakRobeIUsluga() {
                return spisakRobeIUsluga;
            }

            /**
             * Sets the value of the spisakRobeIUsluga property.
             * 
             * @param value
             *     allowed object is
             *     {@link TPrilogUzZahtev }
             *     
             */
            public void setSpisakRobeIUsluga(TPrilogUzZahtev value) {
                this.spisakRobeIUsluga = value;
            }

            /**
             * Gets the value of the punomocje property.
             * 
             * @return
             *     possible object is
             *     {@link TPrilogUzZahtev }
             *     
             */
            public TPrilogUzZahtev getPunomocje() {
                return punomocje;
            }

            /**
             * Sets the value of the punomocje property.
             * 
             * @param value
             *     allowed object is
             *     {@link TPrilogUzZahtev }
             *     
             */
            public void setPunomocje(TPrilogUzZahtev value) {
                this.punomocje = value;
            }

            /**
             * Gets the value of the generalnoPunomocjeRanijePrilozeno property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isGeneralnoPunomocjeRanijePrilozeno() {
                return generalnoPunomocjeRanijePrilozeno;
            }

            /**
             * Sets the value of the generalnoPunomocjeRanijePrilozeno property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setGeneralnoPunomocjeRanijePrilozeno(Boolean value) {
                this.generalnoPunomocjeRanijePrilozeno = value;
            }

            /**
             * Gets the value of the punomocjeCeBitiNaknadnoDostavljeno property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isPunomocjeCeBitiNaknadnoDostavljeno() {
                return punomocjeCeBitiNaknadnoDostavljeno;
            }

            /**
             * Sets the value of the punomocjeCeBitiNaknadnoDostavljeno property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setPunomocjeCeBitiNaknadnoDostavljeno(Boolean value) {
                this.punomocjeCeBitiNaknadnoDostavljeno = value;
            }

            /**
             * Gets the value of the opstiAktOKolektivnomZigu property.
             * 
             * @return
             *     possible object is
             *     {@link TPrilogUzZahtev }
             *     
             */
            public TPrilogUzZahtev getOpstiAktOKolektivnomZigu() {
                return opstiAktOKolektivnomZigu;
            }

            /**
             * Sets the value of the opstiAktOKolektivnomZigu property.
             * 
             * @param value
             *     allowed object is
             *     {@link TPrilogUzZahtev }
             *     
             */
            public void setOpstiAktOKolektivnomZigu(TPrilogUzZahtev value) {
                this.opstiAktOKolektivnomZigu = value;
            }

            /**
             * Gets the value of the dokazOPravuPrvenstva property.
             * 
             * @return
             *     possible object is
             *     {@link TPrilogUzZahtev }
             *     
             */
            public TPrilogUzZahtev getDokazOPravuPrvenstva() {
                return dokazOPravuPrvenstva;
            }

            /**
             * Sets the value of the dokazOPravuPrvenstva property.
             * 
             * @param value
             *     allowed object is
             *     {@link TPrilogUzZahtev }
             *     
             */
            public void setDokazOPravuPrvenstva(TPrilogUzZahtev value) {
                this.dokazOPravuPrvenstva = value;
            }

            /**
             * Gets the value of the dokazOUplatiTakse property.
             * 
             * @return
             *     possible object is
             *     {@link TPrilogUzZahtev }
             *     
             */
            public TPrilogUzZahtev getDokazOUplatiTakse() {
                return dokazOUplatiTakse;
            }

            /**
             * Sets the value of the dokazOUplatiTakse property.
             * 
             * @param value
             *     allowed object is
             *     {@link TPrilogUzZahtev }
             *     
             */
            public void setDokazOUplatiTakse(TPrilogUzZahtev value) {
                this.dokazOUplatiTakse = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Podnosilac_prijave" type="{http://www.ftn.uns.ac.rs/zig}TLice" maxOccurs="unbounded"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "podnosilacPrijave"
    })
    public static class PodnosiociPrijave {

        @XmlElement(name = "Podnosilac_prijave", required = true)
        protected List<TLice> podnosilacPrijave;

        /**
         * Gets the value of the podnosilacPrijave property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the podnosilacPrijave property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPodnosilacPrijave().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TLice }
         * 
         * 
         */
        public List<TLice> getPodnosilacPrijave() {
            if (podnosilacPrijave == null) {
                podnosilacPrijave = new ArrayList<TLice>();
            }
            return this.podnosilacPrijave;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Tip_ziga"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;choice&gt;
     *                   &lt;element name="Individualni_zig" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *                   &lt;element name="Kolektivni_zig" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *                   &lt;element name="Zig_garancije" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *                 &lt;/choice&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Tip_znaka"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;choice&gt;
     *                   &lt;element name="Verbalni_znak" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *                   &lt;element name="Graficki_znak" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *                   &lt;element name="Kombinovani_znak" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *                   &lt;element name="Trodimenzionalni_znak" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *                   &lt;element name="Druga_vrsta_znaka" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *                 &lt;/choice&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Izgled_znaka"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;attribute name="image_url" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Naznacene_boje" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="Boja" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Transliteracija_znaka" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="Prevod_znaka" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="Opis_znaka" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "tipZiga",
        "tipZnaka",
        "izgledZnaka",
        "naznaceneBoje",
        "transliteracijaZnaka",
        "prevodZnaka",
        "opisZnaka"
    })
    public static class Zig {

        @XmlElement(name = "Tip_ziga", required = true)
        protected TipZiga tipZiga;
        @XmlElement(name = "Tip_znaka", required = true)
        protected TipZnaka tipZnaka;
        @XmlElement(name = "Izgled_znaka", required = true)
        protected IzgledZnaka izgledZnaka;
        @XmlElement(name = "Naznacene_boje")
        protected NaznaceneBoje naznaceneBoje;
        @XmlElement(name = "Transliteracija_znaka")
        protected String transliteracijaZnaka;
        @XmlElement(name = "Prevod_znaka")
        protected String prevodZnaka;
        @XmlElement(name = "Opis_znaka")
        protected String opisZnaka;

        /**
         * Gets the value of the tipZiga property.
         * 
         * @return
         *     possible object is
         *     {@link TipZiga }
         *     
         */
        public TipZiga getTipZiga() {
            return tipZiga;
        }

        /**
         * Sets the value of the tipZiga property.
         * 
         * @param value
         *     allowed object is
         *     {@link TipZiga }
         *     
         */
        public void setTipZiga(TipZiga value) {
            this.tipZiga = value;
        }

        /**
         * Gets the value of the tipZnaka property.
         * 
         * @return
         *     possible object is
         *     {@link TipZnaka }
         *     
         */
        public TipZnaka getTipZnaka() {
            return tipZnaka;
        }

        /**
         * Sets the value of the tipZnaka property.
         * 
         * @param value
         *     allowed object is
         *     {@link TipZnaka }
         *     
         */
        public void setTipZnaka(TipZnaka value) {
            this.tipZnaka = value;
        }

        /**
         * Gets the value of the izgledZnaka property.
         * 
         * @return
         *     possible object is
         *     {@link IzgledZnaka }
         *     
         */
        public IzgledZnaka getIzgledZnaka() {
            return izgledZnaka;
        }

        /**
         * Sets the value of the izgledZnaka property.
         * 
         * @param value
         *     allowed object is
         *     {@link IzgledZnaka }
         *     
         */
        public void setIzgledZnaka(IzgledZnaka value) {
            this.izgledZnaka = value;
        }

        /**
         * Gets the value of the naznaceneBoje property.
         * 
         * @return
         *     possible object is
         *     {@link NaznaceneBoje }
         *     
         */
        public NaznaceneBoje getNaznaceneBoje() {
            return naznaceneBoje;
        }

        /**
         * Sets the value of the naznaceneBoje property.
         * 
         * @param value
         *     allowed object is
         *     {@link NaznaceneBoje }
         *     
         */
        public void setNaznaceneBoje(NaznaceneBoje value) {
            this.naznaceneBoje = value;
        }

        /**
         * Gets the value of the transliteracijaZnaka property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTransliteracijaZnaka() {
            return transliteracijaZnaka;
        }

        /**
         * Sets the value of the transliteracijaZnaka property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTransliteracijaZnaka(String value) {
            this.transliteracijaZnaka = value;
        }

        /**
         * Gets the value of the prevodZnaka property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrevodZnaka() {
            return prevodZnaka;
        }

        /**
         * Sets the value of the prevodZnaka property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrevodZnaka(String value) {
            this.prevodZnaka = value;
        }

        /**
         * Gets the value of the opisZnaka property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOpisZnaka() {
            return opisZnaka;
        }

        /**
         * Sets the value of the opisZnaka property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOpisZnaka(String value) {
            this.opisZnaka = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;attribute name="image_url" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class IzgledZnaka {

            @XmlAttribute(name = "image_url")
            protected String imageUrl;

            /**
             * Gets the value of the imageUrl property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getImageUrl() {
                return imageUrl;
            }

            /**
             * Sets the value of the imageUrl property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setImageUrl(String value) {
                this.imageUrl = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="Boja" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "boja"
        })
        public static class NaznaceneBoje {

            @XmlElement(name = "Boja", required = true)
            protected List<String> boja;

            /**
             * Gets the value of the boja property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the boja property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getBoja().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getBoja() {
                if (boja == null) {
                    boja = new ArrayList<String>();
                }
                return this.boja;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;choice&gt;
         *         &lt;element name="Individualni_zig" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
         *         &lt;element name="Kolektivni_zig" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
         *         &lt;element name="Zig_garancije" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
         *       &lt;/choice&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "individualniZig",
            "kolektivniZig",
            "zigGarancije"
        })
        public static class TipZiga {

            @XmlElement(name = "Individualni_zig", defaultValue = "true")
            protected Boolean individualniZig;
            @XmlElement(name = "Kolektivni_zig", defaultValue = "false")
            protected Boolean kolektivniZig;
            @XmlElement(name = "Zig_garancije", defaultValue = "false")
            protected Boolean zigGarancije;

            /**
             * Gets the value of the individualniZig property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isIndividualniZig() {
                return individualniZig;
            }

            /**
             * Sets the value of the individualniZig property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setIndividualniZig(Boolean value) {
                this.individualniZig = value;
            }

            /**
             * Gets the value of the kolektivniZig property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isKolektivniZig() {
                return kolektivniZig;
            }

            /**
             * Sets the value of the kolektivniZig property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setKolektivniZig(Boolean value) {
                this.kolektivniZig = value;
            }

            /**
             * Gets the value of the zigGarancije property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isZigGarancije() {
                return zigGarancije;
            }

            /**
             * Sets the value of the zigGarancije property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setZigGarancije(Boolean value) {
                this.zigGarancije = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;choice&gt;
         *         &lt;element name="Verbalni_znak" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
         *         &lt;element name="Graficki_znak" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
         *         &lt;element name="Kombinovani_znak" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
         *         &lt;element name="Trodimenzionalni_znak" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
         *         &lt;element name="Druga_vrsta_znaka" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
         *       &lt;/choice&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "verbalniZnak",
            "grafickiZnak",
            "kombinovaniZnak",
            "trodimenzionalniZnak",
            "drugaVrstaZnaka"
        })
        public static class TipZnaka {

            @XmlElement(name = "Verbalni_znak", defaultValue = "true")
            protected Boolean verbalniZnak;
            @XmlElement(name = "Graficki_znak", defaultValue = "false")
            protected Boolean grafickiZnak;
            @XmlElement(name = "Kombinovani_znak", defaultValue = "false")
            protected Boolean kombinovaniZnak;
            @XmlElement(name = "Trodimenzionalni_znak", defaultValue = "false")
            protected Boolean trodimenzionalniZnak;
            @XmlElement(name = "Druga_vrsta_znaka", defaultValue = "false")
            protected Boolean drugaVrstaZnaka;

            /**
             * Gets the value of the verbalniZnak property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isVerbalniZnak() {
                return verbalniZnak;
            }

            /**
             * Sets the value of the verbalniZnak property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setVerbalniZnak(Boolean value) {
                this.verbalniZnak = value;
            }

            /**
             * Gets the value of the grafickiZnak property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isGrafickiZnak() {
                return grafickiZnak;
            }

            /**
             * Sets the value of the grafickiZnak property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setGrafickiZnak(Boolean value) {
                this.grafickiZnak = value;
            }

            /**
             * Gets the value of the kombinovaniZnak property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isKombinovaniZnak() {
                return kombinovaniZnak;
            }

            /**
             * Sets the value of the kombinovaniZnak property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setKombinovaniZnak(Boolean value) {
                this.kombinovaniZnak = value;
            }

            /**
             * Gets the value of the trodimenzionalniZnak property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isTrodimenzionalniZnak() {
                return trodimenzionalniZnak;
            }

            /**
             * Sets the value of the trodimenzionalniZnak property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setTrodimenzionalniZnak(Boolean value) {
                this.trodimenzionalniZnak = value;
            }

            /**
             * Gets the value of the drugaVrstaZnaka property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isDrugaVrstaZnaka() {
                return drugaVrstaZnaka;
            }

            /**
             * Sets the value of the drugaVrstaZnaka property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setDrugaVrstaZnaka(Boolean value) {
                this.drugaVrstaZnaka = value;
            }

        }

    }

}
